import type { Help } from "@/lib/help";

// Conteudo de ajuda por tela (gerado + revisado). Telas ausentes usam a descricao do nav.
export const HELP_CONTENT: Record<string, Help> = {
  "integracoes-nfe": {
    resumo: "Central das integrações por API com as plataformas de pagamento (Monetizze, AppMax, Braip, Hotmart, Kiwify, Mercado Pago, PagSeguro, Stripe) e de logística/fiscal — com teste de conexão ao vivo, chaves de API, logs e emissão de NF-e.",
    itens: [
      "Painel: quantas integrações ativas, NF-e autorizadas/com erro, chaves de API e chamadas de API.",
      "Integrações & Teste: clique em Testar para ver, na hora, se cada plataforma está no ar (e se a chave da Monetizze é válida). O teste roda no servidor — sua chave nunca sai do backend.",
      "Chaves de API: gere chaves para sistemas externos consultarem seus dados. A chave aparece uma única vez ao criar.",
      "Nota Fiscal (NF-e): emissões com status, chave, DANFE/XML, e a configuração de baixa de estoque por produto (via VHSYS).",
      "Logs: histórico de chamadas de API e de webhooks recebidos das plataformas.",
    ],
    passos: [
      "Aba Integrações & Teste → clique em Testar todas para checar tudo de uma vez.",
      "Aba Chaves de API → dê um nome, escolha os escopos e clique Gerar chave (copie na hora).",
      "Aba Nota Fiscal → confira as emissões e configure a baixa de estoque por produto.",
    ],
  },
  "admin": {
    resumo: "Painel de configuracao geral do sistema: parametros, recursos que podem ser ligados ou desligados, moedas, idiomas, modulos e informacoes da licenca.",
    itens: [
      "Aba Configuracoes: todos os parametros do sistema, com busca e filtro por categoria; edite o valor e clique em Salvar.",
      "Aba Feature Flags: liga e desliga funcionalidades sem precisar mexer no codigo.",
      "Aba Moedas: taxas de conversao e um conversor multimoeda para calcular valores entre moedas.",
      "Aba Idiomas: idiomas disponiveis na plataforma.",
      "Aba Modulos: quais modulos do ERP estao ativos.",
      "Aba Ambientes e Licenca: dados do plano contratado, status, limite de usuarios e data de validade.",
    ],
    passos: [
      "Na aba Configuracoes, use a busca para achar o parametro.",
      "Altere o valor no campo correspondente.",
      "Clique em Salvar para aplicar.",
    ],
  },
  "aduana": {
    resumo: "Controle do desembaraço aduaneiro: acompanha cada processo na alfândega, o canal de conferência (verde, amarelo, vermelho, cinza), a documentação exigida, as inspeções e a liberação final da carga.",
    itens: [
      "Painel: total de processos, quantos estão em desembaraço, em inspeção, retidos, liberados, documentos pendentes, tempo médio de desembaraço e número de recintos.",
      "Processos: cada processo aduaneiro com código, status, o canal parametrizado e a contagem de documentos obrigatórios ainda pendentes, com a linha do tempo (chegada, registro, canal, inspeção, liberação).",
      "Canais: verde (liberação direta), amarelo (conferência de documentos), vermelho (conferência física) e cinza (suspeita) — você define o canal direto na tela.",
      "Ações rápidas no processo: parametrizar o canal, marcar inspeção OK e liberar o desembaraço (o botão de liberar só funciona quando o processo não está pendente).",
      "Documentos: papéis exigidos por processo (BL, AWB, packing list, invoice, certificados, licenças, manifestos) marcados como obrigatórios ou não e com status pendente/enviado/aprovado/rejeitado.",
      "Recintos: locais alfandegados onde a carga fica — portos, aeroportos, portos secos, terminais, EADI e postos de fronteira.",
    ],
    passos: [
      "Na aba Processos, cadastre um novo processo aduaneiro e ligue-o ao embarque e ao recinto.",
      "Anexe os documentos exigidos na aba Documentos, marcando os obrigatórios.",
      "No processo, escolha o canal e clique em parametrizar; registre a inspeção se houver e clique em liberar desembaraço para soltar a carga.",
    ],
  },
  "analytics": {
    resumo: "Plataforma de dados e BI da logistica: um grande repositorio organizado com catalogo de indicadores, previsoes e controle de qualidade dos dados.",
    itens: [
      "Visao geral com os principais numeros e tendencias do negocio.",
      "Catalogo de KPIs: lista os indicadores por modulo, com definicao padronizada de cada um.",
      "Alertas por limite: cria avisos automaticos quando um KPI passa de um valor (informa nome, KPI, operador, limite e canal).",
      "Catalogo e governanca de dados: lista os ativos de dados com descricao, dominio, tabela de origem, classificacao, nota de qualidade (0-100) e responsavel (Data Owner).",
      "Serve tanto para consultar relatorios quanto para garantir que os dados sao confiaveis e bem cuidados.",
    ],
    passos: [
      "Consulte a visao geral e o catalogo de KPIs para entender os indicadores disponiveis.",
      "Em Alertas por limite, cadastre um novo alerta escolhendo o KPI, o operador, o limite e o canal.",
      "Na governanca de dados, revise a nota de qualidade e o Data Owner de cada ativo.",
    ],
  },
  "ativos-retornaveis": {
    resumo: "Controla os itens que voltam (pallets, containers, gaiolas): quem esta com eles, quando devem voltar, manutencao e cobrancas por atraso ou perda.",
    itens: [
      "Painel com a situação geral dos ativos retornáveis e indicadores de sustentabilidade (ESG).",
      "Tipos de ativos: cadastro dos pallets, containers, gaiolas e demais itens retornáveis.",
      "Empréstimos: registra com quem está cada ativo e a data de devolução prevista.",
      "Manutenção: histórico de serviços e reparos feitos nos ativos.",
      "Cobranças: valores em aberto por retenção, atraso na devolução ou perda de ativos.",
      "Ajuda a reduzir perda de embalagens e a cobrar quem não devolveu.",
    ],
  },
  "auditoria": {
    resumo: "Auditoria logistica e de custos: confere fretes e operacao, aponta riscos, mede rentabilidade e verifica conformidade.",
    itens: [
      "Audita fretes e a operacao para achar cobrancas indevidas, desvios e oportunidades de economia.",
      "Avalia custos e rentabilidade, mostrando onde a operacao ganha ou perde dinheiro.",
      "Matriz de riscos (probabilidade x impacto): cadastra cada risco com area, probabilidade (1-5), impacto (1-5), valor em R$ e plano de acao.",
      "Classifica automaticamente o nivel do risco a partir da probabilidade e do impacto informados.",
      "Apoia compliance e gera um score geral de saude/risco da operacao.",
    ],
    passos: [
      "Cadastre um risco informando area, probabilidade (1-5), impacto (1-5) e valor em R$.",
      "Descreva o plano de acao para tratar aquele risco.",
      "Acompanhe o nivel calculado e priorize os riscos de maior probabilidade e impacto.",
    ],
  },
  "auditoria-fretes": {
    resumo: "Audita o frete cobrado contra o esperado a partir de faturas e CT-e, gera glosas (contestacoes), controla custos logisticos e simula transportadoras.",
    itens: [
      "Aba Painel: indicadores de divergencias, valores auditados e economia.",
      "Aba Faturas & Auditoria: compara por fatura e CT-e o valor cobrado com o esperado e aponta a divergencia.",
      "Aba Glosas: contestacoes de valores cobrados a mais, com motivo, valor e status.",
      "Aba Custos Logisticos: registro de custos por tipo, entidade e competencia.",
      "Aba Simulador: estima e compara o frete entre transportadoras (R$/kg, valor e prazo).",
      "Aba Contratos: contratos de frete com GRIS, Ad Valorem e vigencia.",
    ],
    passos: [
      "Importe as faturas e CT-e das transportadoras.",
      "Rode a auditoria para comparar cobrado x esperado.",
      "Abra glosas para as divergencias e acompanhe a devolucao.",
    ],
  },
  "cadeia-fria": {
    resumo: "Vigia produtos que precisam de temperatura controlada: acompanha sensores, mede a integridade da cadeia fria e dispara alarmes quando a temperatura sai da faixa.",
    itens: [
      "Aba Painel: integridade da cadeia, remessas frias, quantas estão em risco ou rompidas, sensores ativos/offline e alarmes abertos.",
      "Aba Remessas Frias: mostra cada envio refrigerado e se a temperatura saiu da faixa (fora/dentro).",
      "Aba Sensores: cadastro dos sensores IoT e data loggers que medem a temperatura.",
      "Aba Equipamentos: câmaras e equipamentos refrigerados, com aviso de calibração a vencer.",
      "Aba Categorias & Faixas: define as faixas de temperatura permitidas por tipo de produto.",
      "Aba Alarmes: lista os alertas de temperatura fora do padrão para providência.",
    ],
  },
  "central-expedicao": {
    resumo: "Painel inteligente que organiza a expedição em larga escala: agrupa pedidos em ondas de separação, sugere a melhor transportadora, escolhe a embalagem ideal e monta as cargas.",
    itens: [
      "Aba Painel: números do dia (a expedir, confirmados, em separação, embalados, expedidos hoje) e um alerta de filas/gargalos por cor (verde ok, amarelo atenção, vermelho travado).",
      "Botão Gerar ondas: agrupa vários pedidos em uma leva única de separação para o time trabalhar mais rápido.",
      "Aba Escolher Transportadora: informe peso e urgência e o sistema recomenda a transportadora com melhor custo/prazo.",
      "Aba Otimizar Embalagem: sugere qual caixa usar para caber o pedido gastando menos.",
      "Aba Caixas: catálogo das suas embalagens (medidas, peso máximo e custo) que alimenta a sugestão de embalagem.",
      "Aba Cargas: agrupa volumes em pallets, gaiolas, caminhões ou containers para despachar juntos.",
    ],
    passos: [
      "No Painel, clique em Gerar ondas para juntar os pedidos pendentes.",
      "Em Escolher Transportadora, informe o peso e a urgência e veja a recomendação.",
      "Em Cargas, monte a carga com a transportadora e despache.",
    ],
  },
  "comando": {
    resumo: "Sala de comando da operacao em tempo real, onde voce acompanha o estado vivo do negocio, trata alertas e conduz crises.",
    itens: [
      "Aba Mission Control: visao geral do que esta acontecendo agora na operacao inteira.",
      "Aba Central de Alertas: lista os avisos abertos; da para Reconhecer (assumir) e Resolver cada um.",
      "Aba Sala de Crise: abre uma sala dedicada para incidentes graves e registra o passo a passo do que foi feito.",
      "Cada crise guarda um historico de atualizacoes, mantendo todos na mesma pagina durante a emergencia.",
      "Feito para o dia a dia de quem monitora: agir rapido sobre o problema certo, sem procurar em varias telas.",
    ],
    passos: [
      "Abra a Central de Alertas e clique em Reconhecer no alerta que voce vai tratar.",
      "Se for grave, clique em Abrir sala de crise para centralizar o atendimento.",
      "Use Registrar para anotar cada acao tomada na sala de crise.",
      "Ao normalizar, clique em Resolver (alerta) ou Encerrar (crise).",
    ],
  },
  "comex": {
    resumo: "Central de importação e exportação: acompanha processos de compra e venda com o exterior, calcula quanto um produto importado custa depois de todos os impostos e cadastra parceiros, portos, NCMs e documentos.",
    itens: [
      "Painel: números-chave do comércio exterior — importações e exportações abertas, processos parados na aduana, valor FOB em aberto, docs pendentes e saldo de drawback (com aviso do que vence em 60 dias).",
      "Simulador de Importação: você digita FOB, frete, seguro, as alíquotas (II, IPI, PIS, COFINS, ICMS) e despesas, e o sistema calcula o custo nacionalizado (quanto o produto realmente custa no Brasil).",
      "Processos: cada importação ou exportação com Incoterm, parceiro, país de origem/destino, moeda, câmbio, valores, status e números dos documentos oficiais (DI, DUIMP, DU-E, BL/AWB).",
      "Classificação NCM/HS: tabela de códigos fiscais dos produtos com as alíquotas de imposto de cada um — é o que alimenta o simulador.",
      "Parceiros: fornecedores, tradings, despachantes, armadores, agentes de carga, bancos e seguradoras do exterior.",
      "Locais e Documentos: portos, aeroportos, fronteiras e recintos alfandegados; e os papéis de cada processo (invoice, packing list, BL, certificados) com status pendente/recebido/validado. A aba Drawback controla atos concessórios (saldo e prazo).",
    ],
    passos: [
      "Cadastre as NCMs dos seus produtos com as alíquotas na aba Classificação NCM/HS.",
      "Abra a aba Simulador de Importação e preencha FOB, frete, seguro e as alíquotas.",
      "Clique em Simular custo nacionalizado para ver os tributos e o custo final por produto.",
    ],
  },
  "compras": {
    resumo: "Central de compras: aqui você pede materiais, cota preços com fornecedores, emite o pedido e recebe a mercadoria no estoque.",
    itens: [
      "Aba Pedidos: lista os pedidos de compra com fornecedor, previsão de entrega, valor total e status (rascunho, enviado, recebido). Clique em 'abrir' para ver e receber os itens.",
      "Aba Requisições: pedidos internos de compra (o que alguém precisa). Cada um tem código, data-limite ('Necessário até'), justificativa e status que você pode aprovar ali mesmo.",
      "Aba RFQ / Cotações: pedidos de cotação enviados a fornecedores para comparar preços antes de fechar o pedido.",
      "Aba Fornecedores (SRM): cadastro de fornecedores com CNPJ, contato, prazo de entrega (lead time em dias) e um score de 0 a 5.",
      "'+ Novo pedido' já cria o pedido e leva você direto à tela de itens; ao receber, a mercadoria entra no estoque automaticamente.",
    ],
    passos: [
      "Na aba Requisições, clique '+ Nova requisição', informe o que precisa e a data-limite, e aprove.",
      "Na aba Pedidos, clique '+ Novo pedido', escolha o fornecedor e o armazém de recebimento.",
      "Adicione os itens e quantidades no pedido e envie ao fornecedor.",
      "Quando a mercadoria chegar, faça o recebimento no pedido para dar entrada no estoque.",
    ],
  },
  "comunicacao": {
    resumo: "Registra e controla os avisos de rastreio enviados ao comprador por e-mail e WhatsApp, e guarda os modelos de mensagem que você pode editar.",
    itens: [
      "Painel: quantos e-mails e mensagens de WhatsApp foram enviados, quantos deram certo e quantos falharam.",
      "E-mails enviados: lista com destinatário, código de rastreio, assunto, status e a mensagem de retorno do provedor de e-mail.",
      "WhatsApp enviados: lista com nome, telefone, texto da mensagem, status e horário de envio.",
      "Os envios acontecem sozinhos quando o pedido é postado; aqui você só acompanha e vê os erros.",
      "Template E-mail e Template WhatsApp: edite o texto padrão usando variáveis como {{codigo}}, {{nome}} e {{link_rastreio}}.",
      "Template Carteiro: uma variação da mensagem de WhatsApp usada na etapa de entrega.",
    ],
  },
  "control-tower": {
    resumo: "Torre de controle que acompanha os eventos, prazos (SLA) e excecoes da cadeia logistica, destacando o que saiu do combinado.",
    itens: [
      "Concentra os alertas abertos da operacao para voce ver rapidamente o que exige acao.",
      "Acompanha o cumprimento de prazos (SLA): o que esta no prazo e o que estourou.",
      "Mostra eventos e excecoes da cadeia (atrasos, falhas, desvios) conforme acontecem.",
      "Funciona como um radar unico do fluxo logistico, reunindo sinais de varios setores.",
      "Ajuda a priorizar: primeiro o que impacta cliente e prazo, depois o resto.",
    ],
  },
  "coproducao": {
    resumo: "Controla parceiros que ganham comissão sobre as vendas (coprodutores), calcula quanto cada um tem a receber e organiza os repasses por período. Pode dividir o pagamento na hora, via AppMax.",
    itens: [
      "Painel: coprodutores ativos, comissão pendente, valores a repassar e se o split da AppMax está ligado.",
      "Coprodutores: cadastre quem recebe (parceiro, afiliado, sócio) com CPF/CNPJ, chave PIX ou dados bancários e o percentual padrão.",
      "Regras de Comissão: defina o percentual por produto, SKU, cupom ou campanha, e sobre qual base calcular (com ou sem frete/desconto).",
      "Vendas & Comissões: cada venda apurada com o valor total, a comissão calculada e a situação do repasse.",
      "Repasses: agrupa as comissões de um coprodutor num período, mostrando o líquido a pagar e se já foi pago.",
      "Split AppMax e Configuração: credenciais para dividir o pagamento automaticamente e as regras gerais do módulo (prazo de liberação, base de cálculo).",
    ],
  },
  "correios": {
    resumo: "Gestao completa dos Correios: contratos e cartoes de postagem, servicos, PLPs, objetos postados, rastreio (SRO) e auditoria de fretes.",
    itens: [
      "Aba Painel: numeros gerais de postagens, SLA e custos.",
      "Aba Simulador de Frete: informa peso e valor declarado e compara preco e prazo dos servicos.",
      "Aba Objetos: lista os objetos postados com rastreio, servico, destino, peso, frete e status.",
      "Aba Auditoria de Fretes: compara o frete contratado com o cobrado e o peso real com o tarifado, apontando divergencias.",
      "Aba PLPs: pre-listas de postagem (aberta, fechada, coletada, postada) e volumes.",
      "Aba Contratos e Servicos: cadastra contratos, cartoes de postagem e os servicos (expresso, economico, reversa) com SLA e preco.",
    ],
    passos: [
      "Cadastre contratos e servicos nas abas correspondentes.",
      "Use o Simulador de Frete para escolher o melhor servico por peso.",
      "Rode a auditoria de fretes para encontrar cobrancas divergentes.",
    ],
  },
  "dashboard": {
    resumo: "Painel de abertura que reune os principais numeros da operacao logistica em um so lugar, atualizados em tempo real.",
    itens: [
      "Mostra os indicadores (KPIs) mais importantes de todos os setores juntos: estoque, transporte, entregas, custos e pedidos.",
      "Cada cartao traz um numero-chave (ex.: pedidos do dia, entregas no prazo, ocupacao do armazem) para leitura rapida.",
      "Serve como visao executiva: em segundos voce percebe se a operacao vai bem ou se algo precisa de atencao.",
      "Os dados vem direto dos modulos, sem digitacao manual, entao sempre refletem a situacao atual.",
      "E o ponto de partida para navegar aos modulos detalhados quando um numero chama a atencao.",
    ],
  },
  "demanda": {
    resumo: "Planejamento de demanda: registra quanto foi vendido/consumido no passado e projeta quanto você vai precisar nos próximos meses, servindo de base para as compras e a produção.",
    itens: [
      "Aba Previsões: gera uma projeção automática por média móvel escolhendo o produto, o armazém, a janela (quantos meses olhar para trás) e o horizonte (quantos meses prever à frente).",
      "A tabela 'Previsões geradas' mostra produto, mês, método usado e a quantidade prevista.",
      "Aba Histórico: onde você registra a demanda real de cada mês (quantidade, canal de venda e receita) para alimentar a previsão.",
      "Quanto mais histórico registrado, melhor fica a previsão.",
      "As previsões geradas aqui são consumidas pelo MRP como demanda para calcular compras e produção.",
    ],
    passos: [
      "Na aba Histórico, registre a quantidade vendida por mês (use o 1º dia do mês na data).",
      "Volte à aba Previsões e escolha o produto (e opcionalmente o armazém).",
      "Ajuste a janela e o horizonte e clique 'Prever'.",
      "Confira a tabela de previsões geradas logo abaixo.",
    ],
  },
  "devolucoes": {
    resumo: "Gerencia as devoluções de clientes (RMA): abre a solicitação, confere o que voltou, separa em quarentena e decide reintegrar ao estoque, retrabalhar ou descartar.",
    itens: [
      "Aba Painel: RMA em aberto, em inspeção, encerradas, valor devolvido, reembolsos, itens em quarentena e para descarte, e tempo médio.",
      "Aba Devoluções: lista as devoluções e permite abrir uma nova com o botão + Nova devolução.",
      "Aba Motivos: cadastra os motivos padrão de devolução (defeito, arrependimento, erro de envio etc.).",
      "Acompanha cada devolução pelas etapas de conferência, quarentena e destino final.",
      "Mostra o ranking dos motivos mais frequentes para agir na causa.",
    ],
    passos: [
      "Na aba Devoluções, clique em + Nova devolução e informe o pedido e o motivo.",
      "Faça a conferência do que voltou e envie os itens para quarentena.",
      "Defina o destino: reintegrar ao estoque, retrabalhar ou descartar.",
    ],
  },
  "dispositivos": {
    resumo: "Gerencia o uso do GLOP como aplicativo instalavel: aparelhos cadastrados, sincronizacao offline, envio de notificacoes e perfis de operacao.",
    itens: [
      "Instalacao: no celular abra pelo navegador e toque em Adicionar a tela de inicio; no computador clique no icone de instalar na barra de endereco. Telas ja visitadas funcionam offline.",
      "Aba Dispositivos: aparelhos registrados por plataforma, com versao, ultimo acesso e status; da para registrar um novo.",
      "Aba Sincronizacao: fila de dados feitos offline esperando subir para o sistema, com direcao, tentativas e status.",
      "Aba Notificacoes: envia avisos push por categoria (informativo, aprovacao, alerta, lembrete) com titulo e mensagem.",
      "Aba Modos Operacionais: perfis prontos de tela que mostram so os modulos certos para cada funcao (ex.: operador de expedicao).",
    ],
    passos: [
      "Na aba Dispositivos, de um nome ao aparelho e escolha a plataforma.",
      "Clique em Registrar.",
      "Para instalar, siga a instrucao de Adicionar a tela de inicio (celular) ou o icone de instalar (desktop).",
    ],
  },
  "distribuicao": {
    resumo: "Movimenta mercadoria entre unidades e organiza as entregas: transferências entre armazéns e o acompanhamento das entregas aos clientes.",
    itens: [
      "Aba Transferências: cria e acompanha remessas de estoque de um armazém para outro.",
      "Aba Entregas: lista as entregas para clientes e o status de cada uma.",
      "Usa os armazéns cadastrados como origem e destino das transferências.",
      "Serve de ponte entre o estoque interno e a chegada ao cliente.",
    ],
    passos: [
      "Na aba Transferências, crie uma transferência escolhendo armazém de origem e destino.",
      "Acompanhe a saída e a chegada da mercadoria.",
      "Na aba Entregas, monitore a situação de cada entrega ao cliente.",
    ],
  },
  "documentos": {
    resumo: "Cofre digital da empresa: guarda documentos organizados por pasta e categoria, controla versoes, coleta assinaturas e permite buscar por conteudo.",
    itens: [
      "Aba Repositorio: lista de documentos com codigo, titulo, categoria (POP, laudo, contrato, fiscal, ficha tecnica, prontuario), versao e status; da para criar um novo.",
      "Check-out e Check-in: trava o documento para voce editar sem que outra pessoa altere ao mesmo tempo, e depois libera de volta com nova versao.",
      "Aba Assinaturas: documentos aguardando assinatura; assine na hora como eletronica ou por certificado digital, respeitando a ordem dos signatarios.",
      "Aba Retencao: politicas de por quanto tempo guardar cada tipo de documento e o que fazer no vencimento (revisar, arquivar ou descartar).",
      "Aba Busca: procura por titulo ou pelo texto de dentro do documento (leitura OCR), mesmo em arquivos digitalizados.",
    ],
    passos: [
      "Na aba Repositorio, preencha titulo, codigo, categoria e pasta e clique em Criar.",
      "Faca Check-out para editar; ao terminar, faca Check-in para gerar uma nova versao.",
      "Se precisar de assinatura, va na aba Assinaturas e clique em Assinar.",
    ],
  },
  "embarques-internacionais": {
    resumo: "Acompanhamento operacional dos embarques que cruzam fronteiras: cada carga por navio, avião, trem ou caminhão, com a linha do tempo de onde ela está até chegar ao destino.",
    itens: [
      "Painel: total de embarques, quantos são importação e exportação, quantos estão em trânsito, no porto e atrasados, bookings abertos, tempo médio de trânsito, número de agentes e de containers.",
      "Embarques: cada carga com ícone do modal (navio, avião, trem, caminhão), código, status colorido (planejado, reservado, em trânsito, no porto, liberado, entregue), rota origem→destino e Incoterm.",
      "Linha do tempo de cada embarque: bolinha preenchida = evento já aconteceu, bolinha vazia = ainda previsto, cobrindo desde a reserva até a entrega final.",
      "Bookings: reservas de espaço com o armador ou companhia aérea, com número, transportadora, quantidade de containers e status (solicitado, confirmado, rolado, cancelado).",
      "Agentes: empresas parceiras que operam a carga — freight forwarders, NVOCC, armadores, cias aéreas, despachantes e consolidadores.",
      "Incoterms: tabela de referência dos termos de comércio (FOB, CIF etc.) mostrando o ponto em que a responsabilidade passa do vendedor para o comprador.",
    ],
    passos: [
      "Na aba Embarques, cadastre um novo embarque informando código, operação, modal e rota.",
      "Registre a reserva na aba Bookings ligando ao embarque.",
      "Conforme a carga avança, escolha o tipo de evento (embarque, chegada, desembarque...) e clique em registrar evento para atualizar a linha do tempo.",
    ],
  },
  "encomendas": {
    resumo: "Rastreia cada volume/encomenda de ponta a ponta: emite etiquetas, registra as leituras (scans) pelo caminho e acompanha a passagem por hubs e lockers.",
    itens: [
      "Aba Painel: total de volumes, em trânsito, no hub, entregues, devolvidos, scans do dia, etiquetas e hubs congestionados.",
      "Aba Volumes: lista os pacotes com sua etiqueta/identificação (LPN) e situação atual.",
      "Aba Rastreamento: histórico de leituras de cada volume, mostrando por onde passou.",
      "Aba Hubs: cadastra e monitora os centros de triagem por onde os volumes circulam.",
      "Aba Lockers: cadastro dos armários de retirada e quantos volumes aguardam retirada.",
      "Aba Consolidação: agrupa vários volumes em um só envio para ganhar eficiência.",
    ],
  },
  "engenharia-logistica": {
    resumo: "Planejamento de rede logistica com IA: mapeia a demanda, sugere onde abrir centros de distribuicao e simula cenarios com retorno financeiro.",
    itens: [
      "Mapa de demanda (heatmap): mostra onde estao os pedidos e a pressao de volume por regiao.",
      "Planejamento de capacidade: compara a demanda com a capacidade das unidades atuais.",
      "IA de rede: sugere movimentos como Abrir CD, Fechar CD, Abrir Hub, Trocar transportadora, Trocar modal ou Expandir.",
      "Cenarios: monte simulacoes dessas mudancas e compare antes de investir.",
      "Cada cenario estima o resultado (ROI/payback) para embasar a decisao.",
    ],
    passos: [
      "Analise o mapa de demanda e o planejamento de capacidade para achar os gargalos.",
      "Clique em IA rede para receber sugestoes ou em Criar cenario para montar o seu.",
      "Use Simular para ver o resultado projetado.",
      "Se fizer sentido, clique em Aprovar o cenario escolhido.",
    ],
  },
  "envios-rastreamento": {
    resumo: "Acompanha as remessas postadas e o ultimo status, com timeline de eventos, avisos de carteiro ausente, reenvios e cobrancas de reenvio.",
    itens: [
      "Aba Envios: remessas com rastreio, destinatario, CEP/UF, formato, peso, valor pago e ultimo status.",
      "Aba Rastreamento: timeline de eventos de cada objeto, recebidos por rastreio dos Correios.",
      "Aba Destinatarios: dados dos clientes (nome, CPF, CEP, plano, telefone) ligados ao codigo de rastreio.",
      "Aba Carteiro Ausente: avisos de tentativa de entrega, com notificacao ao cliente (WhatsApp/SMS) para reagendar.",
      "Aba Reenvios: gera um novo objeto para vendas cujo pacote se perdeu ou foi devolvido.",
      "Aba Cobrancas de Reenvio: quando o reenvio e pago pelo comprador, cria link de pagamento e acompanha o status.",
    ],
  },
  "estoque": {
    resumo: "Mostra o que voce tem em estoque, quanto vale, o que esta acabando e sugere o que precisa comprar para nao faltar.",
    itens: [
      "Indicadores no topo: SKUs ativos, valor total em estoque, itens abaixo do ponto de pedido, itens vencendo em 30 dias, recebimentos e tarefas em aberto.",
      "Curva ABC: classifica os produtos por importância (A = mais importantes, B = médios, C = menos importantes) para você focar no que rende mais.",
      "Sugestões de ressuprimento: lista os produtos cujo saldo caiu abaixo do ponto de pedido e sugere a quantidade a comprar, com o motivo.",
      "Cada sugestão pode ser marcada como pedida, enviada para Compras ou descartada.",
      "Busca por nome ou código para achar rápido um produto e ver seu saldo e valor.",
      "O valor em estoque é calculado somando saldo x custo de cada produto.",
    ],
    passos: [
      "Clique em Recalcular curva ABC para reclassificar os produtos por importância.",
      "Clique em Gerar sugestões de ressuprimento para o sistema comparar saldo com ponto de pedido.",
      "Na lista de sugestões, envie para Compras o que precisa repor ou descarte o que não faz sentido.",
    ],
  },
  "estoque-logistico": {
    resumo: "Controle pratico de estoque por produto e por local: cada entrada, saida, ajuste ou transferencia vira um movimento, e a venda despachada baixa o estoque automaticamente.",
    itens: [
      "Painel: total de produtos, locais de estoque, movimentos, entradas, saídas, baixas automáticas configuradas e registros de estoque.",
      "Produtos: cadastro com estoque mínimo e custo.",
      "Locais: os pontos de armazenagem; o saldo é calculado por local a partir dos movimentos.",
      "Movimentos: cada entrada, saída, ajuste ou transferência, identificados por cor.",
      "Baixa Automática: abate o estoque sozinho a cada venda despachada.",
      "Registros de Estoque: guardam a conferência (etiqueta/declaração) de cada objeto, com apoio de IA.",
    ],
  },
  "expedicao": {
    resumo: "Central de saída de mercadorias: registra os pedidos que vão sair do estoque e cuida da separação, embalagem e embarque para o cliente.",
    itens: [
      "Aba Pedidos: lista os pedidos de saída e acompanha o andamento (confirmado, em separação, embalado, expedido).",
      "Aba Clientes: cadastra e mantém os clientes que recebem os pedidos (nome, CPF/CNPJ, cidade, telefone, limite de crédito).",
      "Abre cada pedido para ver os itens e avançar as etapas de picking, packing e embarque.",
      "Liga cada saída ao estoque, ao cliente e ao armazém de origem.",
    ],
    passos: [
      "Cadastre o cliente na aba Clientes (nome e documento).",
      "Na aba Pedidos, crie um novo pedido de saída escolhendo o cliente e o armazém.",
      "Adicione os itens e avance o pedido pelas etapas até o embarque.",
    ],
  },
  "frota": {
    resumo: "Gestao avancada da frota propria: viagens, custos por km, combustivel, manutencao, cotacao/leilao de fretes e pegada de carbono.",
    itens: [
      "Aba Painel: visao geral com custos, insights de IA e pegada de carbono dos ultimos 30 dias.",
      "Aba Viagens: registra cada viagem (origem, destino, veiculo, motorista, distancia) e mostra custo total e R$/km.",
      "Aba Manutencao: servicos por veiculo (preventiva, corretiva, pneus, oleo) com custo e proxima data.",
      "Aba Combustivel: abastecimentos com litros, custo e odometro por veiculo.",
      "Aba Cotacoes e Lances: abre uma cotacao de frete, recebe lances das transportadoras e adjudica o vencedor.",
      "Aba Contratos: contratos de frete vinculados as transportadoras.",
    ],
    passos: [
      "Cadastre viagens e vincule veiculo e motorista.",
      "Registre abastecimentos e manutencoes para o sistema calcular o custo por km.",
      "Para comprar frete, abra uma cotacao, veja os lances e adjudique o melhor.",
    ],
  },
  "gemeo-digital": {
    resumo: "Copia viva da sua operacao onde e possivel testar mudancas (what-if) sem risco, identificar gargalos e reproduzir o historico.",
    itens: [
      "Aba Simulacoes What-If: cria testes de cenarios como Aumento de demanda, Novo CD, Novo Hub, Nova transportadora, Fechamento de unidade, Mudanca de rota ou modal.",
      "Simula tambem eventos externos: Greve, Bloqueio rodoviario, Evento climatico, Acidente e Interrupcao geral.",
      "Aba Gargalos: aponta os pontos que travam a operacao e precisam de atencao.",
      "Mostra o impacto estimado de cada simulacao em indicadores como SLA %.",
      "Permite reproduzir situacoes passadas para entender o que aconteceu e evitar repetir erros.",
    ],
    passos: [
      "Na aba Simulacoes What-If, escolha o tipo de evento que quer testar.",
      "Rode a simulacao e aguarde o resultado (Simulando...).",
      "Compare o impacto no SLA e nos gargalos antes de aplicar a mudanca na operacao real.",
    ],
  },
  "ia-central": {
    resumo: "Cerebro operacional do ERP: agentes de inteligencia artificial que analisam a operacao, sugerem decisoes e guardam o conhecimento da empresa.",
    itens: [
      "Aba Agentes: mostra os assistentes de IA ativos e o que cada um monitora.",
      "Aba Decisoes: traz recomendacoes da IA que ficam pendentes para voce Aprovar ou Rejeitar.",
      "Painel de resumo com agentes ativos, decisoes a aprovar e alertas do dia.",
      "Memoria Corporativa (RAG): base de conhecimento com politicas, procedimentos (POP), normas ISO, LGPD, contratos e manuais.",
      "A IA usa essa memoria para responder e recomendar com base nas regras reais da sua empresa.",
      "Traz um briefing executivo resumindo a situacao geral gerado automaticamente.",
    ],
    passos: [
      "Abra a aba Decisoes e leia a recomendacao proposta pela IA.",
      "Clique em Aprovar para aplicar ou Rejeitar para descartar.",
      "Para ensinar a IA, cadastre documentos na Memoria Corporativa informando titulo, tipo e conteudo.",
    ],
  },
  "importacao-pedidos": {
    resumo: "Traz pedidos de qualquer origem (planilha, arquivo, colagem) para dentro do sistema já lidos, conferidos e sem duplicidade, prontos para virar pedido de verdade.",
    itens: [
      "Painel: quantos arquivos e pedidos entraram, quantos foram validados, quantos estão com pendência, duplicados ou já promovidos, e a taxa de promoção.",
      "Importar: cole os dados em formato de planilha (CSV com cabeçalho) ou lista, e o sistema lê linha por linha automaticamente.",
      "Central de Pendências: mostra os pedidos que precisam de atenção (CPF/CNPJ, CEP, telefone ou peso com problema) para corrigir antes de seguir.",
      "Regras: define as regras que o sistema usa para validar e organizar os pedidos, por ordem de prioridade.",
      "Arquivos: histórico de tudo que já foi importado, com data de recebimento.",
      "Cada pedido passa por etapas com cores: Lido, Validado, Pendência, Duplicado, Promovido ou Rejeitado.",
    ],
    passos: [
      "Abra a aba Importar e cole os pedidos (planilha ou lista).",
      "Clique para importar; o sistema lê e confere cada linha.",
      "Vá em Central de Pendências e corrija o que estiver marcado com problema.",
      "Promova os pedidos validados para que virem pedidos oficiais.",
    ],
  },
  "integracoes": {
    resumo: "Central que conecta o ERP a outros sistemas: publica APIs, dispara e recebe avisos automaticos (webhooks), controla filas de mensagens e importa dados de fora.",
    itens: [
      "Aba API Marketplace e Conectores: catalogo das APIs publicadas e das conexoes com sistemas externos.",
      "Aba Event Bus e Webhooks: publica eventos (ex.: pedido criado) e cadastra webhooks para avisar outros sistemas automaticamente quando algo acontece.",
      "Aba Fila de Mensagens: mensagens em transito com tentativas e status; itens que falharam (dead-letter) podem ser reprocessados.",
      "Aba Fluxos ETL: importacoes e transformacoes de dados em lote entre sistemas.",
      "Aba Chaves de API: gera chaves de acesso internas do GLOP (copie na hora, nao aparecem de novo).",
      "Atencao: para colar a chave da Monetizze/Hotmart/Kiwify e puxar pedidos da loja, use a tela Puxar Pedidos de Lojas, nao esta.",
    ],
    passos: [
      "Para gerar acesso, va em Chaves de API, digite um nome e clique em Gerar chave; copie imediatamente.",
      "Para avisar outro sistema, va em Event Bus e Webhooks e cadastre a URL de destino e o evento.",
      "Se uma mensagem falhar na Fila, clique em reprocessar.",
    ],
  },
  "integracoes-lojas": {
    resumo: "Tela para trazer automaticamente para o sistema todos os pedidos vendidos nas plataformas (Monetizze, Hotmart, Kiwify e outras). Cole a chave da loja e puxe as vendas.",
    itens: [
      "Escolha a loja/produtor nos botões do topo ou clique em + loja para cadastrar uma nova.",
      "Cole a chave da API da plataforma e clique em conectar chave; ela fica guardada com o selo Configurada.",
      "Puxar todos os pedidos traz o histórico completo; Sincronizar novas vendas busca só o que entrou desde a última vez.",
      "Os quatro números mostram: vendas recebidas, importadas, quantas ficaram sem plano de preço e o valor total.",
      "A tabela lista cada venda com comprador, produto, status e valor; o código laranja Sem plano avisa que falta cadastrar preço/plano do produto.",
      "Na coluna Rastreio você digita o código dos Correios e o botão 📮 devolve o rastreio à plataforma, que avisa o comprador. Puxar de novo nunca duplica pedidos.",
    ],
    passos: [
      "Selecione a loja (ou clique em + loja para criar) e cole a chave da API no campo indicado.",
      "Clique em conectar chave para guardá-la.",
      "Clique em Puxar todos os pedidos e acompanhe o progresso; depois use Sincronizar novas vendas no dia a dia.",
      "Preencha o código de rastreio na venda e clique em 📮 para notificar o comprador pela plataforma.",
    ],
  },
  "integracoes-transportadoras": {
    resumo: "Hub de integracao por API com Correios e qualquer transportadora: conecta, cota, gera etiqueta, rastreia e guarda credenciais com log de chamadas.",
    itens: [
      "Aba Painel: status das integracoes por provedor.",
      "Aba Cotacao Comparativa: informa peso, valor e zona e compara frete e prazo entre as transportadoras conectadas.",
      "Aba Conectores: cadastra a integracao (Correios, Jadlog, Braspress, Loggi, Mercado Envios e outros) com URL, tipo de autenticacao e ambiente.",
      "Aba Operacoes: define quais acoes cada conector faz (cotar, expedir, etiqueta, rastreio, coleta).",
      "Aba Credenciais: cofre de chaves e senhas de acesso, guardadas de forma protegida.",
      "Aba Logs: historico das chamadas com data, operacao, codigo HTTP, tempo de resposta e resultado.",
    ],
    passos: [
      "Cadastre o conector da transportadora na aba Conectores.",
      "Informe as chaves de acesso na aba Credenciais e teste a conexao.",
      "Use a Cotacao Comparativa para escolher a melhor transportadora.",
    ],
  },
  "inventario": {
    resumo: "Organiza as contagens de estoque (conferencia fisica do que existe de verdade) e o rastreio da historia de cada lote de produto.",
    itens: [
      "Lista das contagens com código, tipo, data, armazém e situação (Aberta, Contando, Revisão, Fechada ou Cancelada).",
      "Contagem cíclica: contagens periódicas de partes do estoque, sem parar tudo de uma vez.",
      "Botão para criar uma nova contagem informando código, armazém e tipo.",
      "Ao abrir uma contagem, você registra as quantidades contadas e compara com o saldo do sistema.",
      "Genealogia de lote: permite acompanhar de onde veio e para onde foi cada lote de produto.",
    ],
    passos: [
      "Clique em Nova contagem e escolha o armazém e o tipo.",
      "Abra a contagem criada e registre as quantidades conferidas fisicamente.",
      "Revise as diferenças e feche a contagem para ajustar o estoque.",
    ],
  },
  "logia": {
    resumo: "Central de insights logisticos: a IA transforma os dados da operacao em previsoes e planos de acao praticos.",
    itens: [
      "Reune insights automaticos sobre o que esta acontecendo e o que tende a acontecer.",
      "Apresenta previsoes (ex.: demanda, atrasos, rupturas) para voce se antecipar.",
      "Sugere planos de acao concretos, e nao apenas numeros soltos.",
      "Ajuda quem decide a focar nas oportunidades e riscos mais relevantes.",
      "Complementa os paineis: enquanto o dashboard mostra o numero, aqui voce ve o porque e o que fazer.",
    ],
  },
  "logistica-reversa": {
    resumo: "Controla todo o ciclo reverso de forma estruturada: autoriza o retorno, agenda a coleta, recebe, faz a triagem, dá a destinação e ainda gerencia recalls e embalagens retornáveis.",
    itens: [
      "Aba Painel: retornos, aguardando autorização, em processo, aguardando destinação, taxa de reaproveitamento, valor recuperado e recalls ativos.",
      "Aba Retornos: acompanha cada retorno por um fluxo de botões — autorizar, agendar coleta, coletado, receber, triar e destinar.",
      "Aba Recalls: gerencia campanhas de recolhimento de produtos.",
      "Aba Embalagens Retornáveis: controla embalagens que circulam e voltam, mostrando quantas estão fora e quantas se perderam.",
      "Registra a destinação final (reaproveitar, reciclar, descartar) e o valor recuperado.",
    ],
    passos: [
      "Na aba Retornos, autorize a solicitação (gera o RMA).",
      "Agende a coleta e marque como coletado e recebido conforme avança.",
      "Faça a triagem e defina a destinação do item.",
    ],
  },
  "manutencao": {
    resumo: "Manutenção de frota e ativos (EAM): controla equipamentos e veículos, abre ordens de serviço, programa a manutenção preventiva e acompanha falhas e indicadores de confiabilidade.",
    itens: [
      "Aba Ordens de serviço: lista as OS de manutenção (preventiva, corretiva etc.) ligadas a cada ativo.",
      "Aba Ativos: cadastro de equipamentos, veículos e instrumentos com patrimônio, tipo, criticidade, status e hierarquia (planta > área > linha > equipamento via 'Ativo pai').",
      "Aba Planos preventivos: planos por calendário, horas, KM ou ciclos; o botão 'Gerar OS dos planos vencidos' cria automaticamente as ordens dos planos com data vencida.",
      "Aba Falhas: histórico de falhas com causa raiz (RCA: 5 Porquês, Ishikawa, FMEA) e tempo de parada em minutos.",
      "Aba Leituras: leituras de condição (vibração, temperatura, corrente) com limites mínimo e máximo; valor fora do limite vira alerta.",
      "Alimenta indicadores como MTTR (tempo médio de reparo) e MTBF (tempo médio entre falhas).",
    ],
    passos: [
      "Na aba Ativos, cadastre o equipamento ou veículo com patrimônio e criticidade.",
      "Na aba Planos preventivos, crie um plano com gatilho (calendário/horas/KM) e a próxima data.",
      "Clique 'Gerar OS dos planos vencidos' para abrir as ordens automaticamente.",
      "Acompanhe a execução na aba Ordens de serviço e registre falhas quando houver.",
    ],
  },
  "mdm": {
    resumo: "Governanca dos dados-mestre: garante que cadastros como produtos, clientes e fornecedores sejam unicos, corretos e confiaveis para toda a empresa.",
    itens: [
      "Aba Dominios e Qualidade: nota de qualidade de cada area de cadastro (produtos, clientes, colaboradores, fornecedores) e quem e o responsavel (owner e steward).",
      "Aba Duplicidades: encontra cadastros repetidos e mostra os pares suspeitos lado a lado para voce decidir qual manter (Manter A ou Manter B).",
      "Aba Linhagem e Glossario: mostra de onde vem e para onde vai cada dado, e um dicionario de termos do negocio com suas definicoes.",
      "Aba Governanca: solicitacoes de mudanca (criar, alterar, inativar, reativar) que passam por aprovacao antes de mexer no cadastro oficial.",
      "Botao de avaliacao de qualidade: roda a analise por dominio para atualizar as notas.",
    ],
    passos: [
      "Va na aba Duplicidades e clique em detectar duplicados no dominio desejado.",
      "Compare os dois registros mostrados lado a lado.",
      "Clique em Manter A ou Manter B para unificar e eliminar a repeticao.",
    ],
  },
  "nfe": {
    resumo: "Acompanha a emissao das notas fiscais eletronicas (via VHSYS): status, chave, DANFE e XML, e o vinculo que faz a venda dar baixa no estoque.",
    itens: [
      "Painel: total de emissões, quantas foram emitidas/autorizadas, quantas deram erro, pendentes, valor emitido e configurações de baixa.",
      "Emissões: cada nota gerada com seu status, chave, protocolo, DANFE e XML para consulta.",
      "Falhas ficam marcadas com o erro e o número de tentativas de reenvio.",
      "Baixa de Estoque (Vhsys): vincula cada produto ao seu id de produto/local no VHSYS para dar baixa automática ao emitir a nota.",
      "Cada venda elegível gera automaticamente uma emissão de NFe.",
    ],
    passos: [
      "Na aba Emissões, acompanhe o status de cada nota (autorizada, pendente ou com erro).",
      "Para notas com erro, verifique a mensagem e reenvie.",
      "Na aba Baixa de Estoque, vincule o produto ao id do VHSYS para a baixa automática funcionar.",
    ],
  },
  "operacao-armazem": {
    resumo: "A operacao inteligente do armazem: usa IA para dizer onde guardar cada produto, gera tarefas de reabastecimento, acompanha produtividade e ate o impacto ambiental.",
    itens: [
      "Painel: ocupação do armazém (em %), total de posições, tarefas pendentes e concluídas hoje, ondas abertas, recebimentos em aberto e congestão por zona.",
      "Slotting (IA): recomendações de onde é melhor guardar cada produto para agilizar a operação; você aplica com um clique.",
      "Reabastecimento: gera automaticamente as tarefas de repor os pontos de separação a partir do estoque de reserva.",
      "Produtividade: acompanha o desempenho das tarefas e da equipe.",
      "Sustentabilidade (ESG): indicadores do impacto ambiental da operação.",
      "Botão IA armazém gera insights e recomendações inteligentes sobre a operação.",
    ],
    passos: [
      "No Painel, veja a ocupação e onde há congestão de tarefas.",
      "Clique em Reabastecer para o sistema gerar as tarefas de reposição.",
      "Na aba Slotting (IA), aplique as recomendações de melhor posição para cada produto.",
    ],
  },
  "patio": {
    resumo: "Gestao avancada do patio e portaria: check-in/out com OCR, mapa de vagas, filas, balancas, carga/descarga, containers, lacres e indicadores.",
    itens: [
      "Aba Painel e Mapa: visao geral do patio e mapa visual das vagas por status (livre, ocupada, reservada, bloqueada).",
      "Aba Portaria/Portarias: registro de entradas e saidas (motorista, placa, transportadora, documento) e cadastro das portarias, com apoio de leitura de placa (LPR).",
      "Aba Vagas e Fila: posicoes por corredor/tipo (caminhao, carreta, container) e a fila de veiculos aguardando por prioridade.",
      "Aba Balanca e Carga/Descarga: pesagens e o acompanhamento das operacoes de carga e descarga com duracao.",
      "Aba Containers e Lacres: controle de containers e lacres de seguranca.",
      "Aba Credenciais, Visitantes, SLA e Performance: cracha/QR/RFID de acesso, registro de visitantes (LGPD), tempos por transportadora e indicadores de desempenho.",
    ],
    passos: [
      "Cadastre portarias, vagas e docas do patio.",
      "Faca o check-in do veiculo na portaria (com OCR de placa e documento).",
      "Acompanhe o veiculo pela fila, pesagem e carga/descarga ate a saida.",
    ],
  },
  "pedidos-logisticos": {
    resumo: "Central onde cada pedido nasce como demanda e caminha, passo a passo, até a entrega e o encerramento. É a origem do fluxo que atualiza os outros setores.",
    itens: [
      "Painel: veja o resumo e quantas ordens estão paradas em cada etapa do processo.",
      "Ordens: lista dos pedidos abertos, com os botões de ação certos para o momento de cada um.",
      "Cada pedido segue um roteiro: demanda, validação, planejamento, reserva de estoque e as etapas seguintes até entregar.",
      "Validar (ATP) confere se há estoque disponível; Planejar escolhe o depósito e a transportadora; Reservar estoque separa as unidades.",
      "Dá para Bloquear (informando o motivo) ou Cancelar um pedido a qualquer momento.",
      "Aba Fluxo (17 etapas) mostra o roteiro completo e a aba Eventos registra tudo que aconteceu, com data e hora.",
    ],
    passos: [
      "Clique em + Nova demanda e preencha produto, quantidade, depósito e transportadora.",
      "Na aba Ordens, clique em Validar (ATP) para conferir a disponibilidade.",
      "Clique em Planejar e depois em Reservar estoque para separar as unidades.",
      "Use Avançar para levar o pedido à próxima etapa até a entrega.",
    ],
  },
  "planos-precos": {
    resumo: "Onde se define, para cada produtor, os planos das plataformas, os preços dos produtos e as regras de embalagem, frete e peso usadas para gerar a etiqueta dos Correios.",
    itens: [
      "Painel: total de planos, quantos geram prepostagem sozinhos, preços cadastrados e faixas de frete e peso.",
      "Planos: liga o código do plano da plataforma a uma regra de embalagem e define se gera prepostagem e atualiza rastreio automaticamente.",
      "Preços por Produto e Tabela de Preços: valor unitário por código de produto e por faixa de quantidade (com link de pagamento opcional).",
      "Regras de Produto: peso e dimensões da embalagem; palavras-chave casam o produto e a regra fallback vale quando nenhuma outra se aplica.",
      "Faixas de Frete e Faixas de Peso: ajustam o valor do frete e o peso total conforme a quantidade de itens da venda.",
      "Tudo é organizado por produtor, então cada parceiro pode ter seus próprios preços e regras.",
    ],
  },
  "portal-cliente": {
    resumo: "Area onde seu cliente acompanha as entregas dele e fala com voce: ele ve o andamento do pedido, abre chamados, pede troca ou devolucao e baixa documentos. Aqui voce administra tudo isso do lado da empresa.",
    itens: [
      "Painel: numeros rapidos do atendimento (chamados abertos, chamados com prazo/SLA vencido, tempo medio de resolucao, satisfacao CSAT, nota NPS, devolucoes em aberto, usuarios do portal e documentos).",
      "Chamados: lista de solicitacoes dos clientes com numero, assunto, prioridade, status e prazo (SLA). O aviso 'vencido' em vermelho mostra o que passou do prazo combinado.",
      "Ao abrir um chamado voce ve a conversa (mensagens do cliente e do atendente), pode responder na hora e marcar como resolvido.",
      "RMA / Devolucoes: registra e acompanha pedidos de devolucao, troca, garantia ou credito, com status desde solicitado ate concluido.",
      "Usuarios do Portal: cadastra as pessoas de cada cliente (comprador, financeiro, tecnico) e gera um codigo de acesso para elas entrarem na area do cliente; da pra copiar o codigo com um clique.",
      "Documentos: disponibiliza notas fiscais, boletos, contratos, laudos e comprovantes por cliente. Base de Conhecimento: publica manuais, fichas tecnicas, FISPQ, videos e perguntas frequentes.",
      "Botao 'Abrir rastreio publico' leva a pagina de rastreamento que qualquer cliente acessa sem senha.",
    ],
    passos: [
      "Abra a aba Chamados e clique em '+ Novo chamado' para registrar uma solicitacao (cliente, assunto, prioridade e descricao).",
      "Clique em 'abrir' num chamado para ver a conversa, digite sua resposta e clique em Responder; quando terminar, clique em Resolver.",
      "Na aba Usuarios do Portal, cadastre a pessoa do cliente e copie o codigo de acesso para enviar a ela.",
    ],
  },
  "pos-venda": {
    resumo: "Central de pos-venda para cuidar do cliente depois da entrega: registra reclamacoes e problemas (ocorrencias), mede a satisfacao com pesquisas NPS/CSAT e acompanha os avisos enviados ao cliente. Tambem oferece a pagina publica de rastreio.",
    itens: [
      "Painel: indicadores de satisfacao e atendimento (NPS colorido por faixa, CSAT de 1 a 5, % de entregas no prazo, total de pesquisas, ocorrencias abertas e resolvidas, tempo medio de resolucao e devolucoes em aberto).",
      "Ocorrencias: lista de problemas relatados pelo cliente (pedido atrasado, nao recebido, avariado, produto incorreto, extravio, entre outros), com tipo, cliente e prioridade; o numero ao lado da aba mostra quantas existem.",
      "Cada ocorrencia aberta tem um botao 'Resolver' para marca-la como resolvida na hora.",
      "Pesquisas (NPS): mostra as respostas dos clientes com nota NPS (verde bom, amarelo neutro, vermelho ruim), CSAT, se chegou no prazo, se veio integro e o comentario deixado.",
      "Notificacoes: historico dos avisos enviados ao cliente, com canal (ex.: e-mail, WhatsApp), evento, status e data de envio.",
      "Botao 'IA churn' aciona a inteligencia (LOGIA) para sinalizar clientes em risco de deixar de comprar; 'Pagina publica de rastreio' abre o rastreamento aberto ao cliente.",
    ],
    passos: [
      "Na aba Ocorrencias, use 'Registrar ocorrencia' para lancar um problema do cliente (cliente, tipo, prioridade e descricao).",
      "Quando o problema for resolvido, clique em 'Resolver' na ocorrencia correspondente.",
      "Clique em 'IA churn' para gerar a lista de clientes em risco e priorizar o contato de retencao.",
    ],
  },
  "postagens": {
    resumo: "Torre de controle das postagens (Correios e transportadoras): acompanha etiquetas e PLP, o que ainda não foi postado, objetos parados sem movimentação e problemas como CEP inválido ou SLA estourado.",
    itens: [
      "Aba Painel: aguardando postagem, postados hoje, sem 1ª movimentação, problemas abertos e críticos, entregues e tempo médio de postagem.",
      "Aba Aguardando Postagem: objetos com etiqueta gerada que ainda não foram postados.",
      "Aba Sem Movimentação: objetos parados, sem a primeira leitura do transportador, que precisam de atenção.",
      "Aba Problemas: lista de pendências (CEP inválido, SLA em risco, objeto parado) com botão Resolver.",
      "Botão Verificar agora: roda a checagem automática que detecta os problemas de postagem.",
    ],
    passos: [
      "Clique em Verificar agora para o sistema detectar problemas.",
      "Na aba Problemas, revise cada pendência e clique em Resolver após tratar.",
      "Acompanhe na aba Sem Movimentação os objetos parados e cobre o transportador.",
    ],
  },
  "prepostagem": {
    resumo: "Controla as pre-postagens dos Correios (PPN), o rastreio dos objetos, a conferencia do que foi realmente postado e as correcoes de CEP.",
    itens: [
      "Aba Painel: resumo das pre-postagens e do andamento.",
      "Aba Prepostagens: objetos gerados no fluxo de despacho com destinatario, cidade/UF, servico, peso e status.",
      "Aba Rastreio (PPN): sincroniza o ultimo status e a localizacao dos objetos direto dos Correios.",
      "Aba Conferencia: compara a planilha/PDF de postagem com o que foi postado (postados x nao encontrados).",
      "Aba Correcoes de CEP: registra CEPs corrigidos automaticamente antes do envio, evitando devolucoes.",
      "Aba Logs Automaticos: cada etapa da geracao automatica de pre-postagem por venda (plataforma, plano, etapa, status).",
    ],
  },
  "processos": {
    resumo: "Motor de automacao de processos: aqui voce cria fluxos de aprovacao, acompanha o que esta em andamento e responde as tarefas que caem na sua caixa.",
    itens: [
      "Aba Painel: numeros gerais de processos ativos, tarefas pendentes e prazos (SLA) a vencer.",
      "Aba Minhas Tarefas: o que espera a sua decisao. Cada item mostra o prazo, aceita um comentario e tem os botoes Aprovar e Reprovar.",
      "Aba Instancias: cada processo que ja foi iniciado, com titulo, etapa atual e status; da para iniciar um novo escolhendo o processo e dando um titulo.",
      "Aba Processos: a lista de fluxos publicados (modelos) que a empresa pode usar.",
      "Aba Regras de Negocio: regras do tipo SE isto ENTAO aquilo (DMN), com um testador para simular um valor e ver o resultado antes de valer para todos.",
    ],
    passos: [
      "Va em Minhas Tarefas e localize o item que espera voce.",
      "Se quiser, escreva um comentario explicando a decisao.",
      "Clique em Aprovar ou Reprovar; o processo segue sozinho para a proxima etapa.",
    ],
  },
  "produtos": {
    resumo: "Onde voce cadastra cada produto (SKU) com todos os seus detalhes: nome, código de barras, categoria, marca, medidas, peso, impostos e regras de estoque.",
    itens: [
      "Identificação: nome, SKU, código, código de barras (GTIN) e descrição curta do produto.",
      "Classificação: tipo do produto, categoria, marca, modelo, segmento e classes ABC/XYZ (importância e previsibilidade).",
      "Dimensões: peso líquido e bruto, altura, largura, comprimento, cubagem e empilhamento máximo.",
      "Tributação: campos fiscais como NCM, CEST, CFOP e origem, usados na nota fiscal.",
      "Estoque: estoque mínimo/máximo, ponto de pedido, estoque de segurança, prazo de reposição e se o produto exige lote, validade ou número de série.",
      "Marca produtos que são perecíveis ou perigosos, e o custo e preço de venda.",
    ],
    passos: [
      "Clique em novo produto e preencha o nome (obrigatório) na aba Identificação.",
      "Percorra as abas preenchendo classificação, medidas, impostos e regras de estoque.",
      "Salve; o produto passa a existir para estoque, compras e vendas.",
    ],
  },
  "rede-logistica": {
    resumo: "Mapa da malha logistica global: pontos (CDs, hubs, regioes), conexoes entre eles, capacidade, cobertura e simulacao estrategica da rede.",
    itens: [
      "Mostra os nos da rede (centros de distribuicao, hubs, regioes e pontos de coleta) e as conexoes (lanes) entre eles.",
      "Painel de cobertura e balanceamento: regioes cobertas, numero de conexoes e capacidade total.",
      "Aba Simulacoes de Rede: testa mudancas como Novo CD, Novo Hub, Nova regiao, Nova conexao, Nova transportadora ou Fechar unidade.",
      "Simula tambem cenarios de estresse: Aumento de demanda, Rebalancear, Crise logistica e Evento climatico.",
      "Ajuda a decidir onde vale expandir, fechar ou redistribuir para melhorar cobertura e custo.",
    ],
    passos: [
      "Confira o painel de cobertura e balanceamento para ver onde falta ou sobra capacidade.",
      "Na aba Simulacoes de Rede, escolha a mudanca que deseja avaliar.",
      "Rode a simulacao e compare cobertura e capacidade antes de decidir.",
    ],
  },
  "seguranca": {
    resumo: "Controle de identidade e seguranca: quem entra, com quais permissoes, com autenticacao reforcada (MFA), acessos temporarios e resposta a incidentes.",
    itens: [
      "Aba Identidades: lista de usuarios com tipo, se e conta privilegiada, se tem MFA ativo e o nivel de risco.",
      "Sessoes ativas: quem esta logado agora, em qual dispositivo e IP, com opcao de encerrar a sessao.",
      "Aba Acesso Privilegiado (PAM): pedidos de acesso elevado e temporario, com justificativa e prazo de horas; um responsavel aprova ou nega.",
      "Aba Incidentes: registros de eventos de seguranca que podem ser marcados como resolvidos.",
      "Aba Politicas (Zero Trust): regras de quem pode o que (RBAC, ABAC, Zero Trust), com efeito permitir ou negar e prioridade.",
      "Aba Certificacoes: campanhas periodicas para revisar e confirmar quem ainda deve ter cada acesso.",
    ],
    passos: [
      "Na aba Acesso Privilegiado, informe o privilegio, a justificativa e por quantas horas precisa.",
      "Clique em Solicitar; o pedido fica pendente.",
      "Um responsavel entra e clica em Aprovar ou negar; se aprovado, o acesso expira sozinho no prazo.",
    ],
  },
  "tms": {
    resumo: "Central de transporte: cadastra transportadoras, veiculos, motoristas e tabelas de frete, e ainda calcula o custo de um envio.",
    itens: [
      "Aba Embarques: acompanha as cargas/envios registrados e seus dados.",
      "Aba Transportadoras: cadastro com nome, CNPJ, modal (rodoviario, aereo, maritimo...), contato e nota de 0 a 5.",
      "Aba Frota: veiculos com placa, tipo, marca/modelo e capacidade (peso, volume e pallets).",
      "Aba Motoristas: nome, CPF, CNH e categoria, vinculados a uma transportadora.",
      "Aba Tabelas de Frete: faixas de preco por transportadora, UF de destino e faixa de peso.",
      "Aba Calculadora: usa as tabelas cadastradas para estimar o frete de um envio.",
    ],
    passos: [
      "Cadastre as transportadoras na aba Transportadoras.",
      "Na aba Tabelas de Frete, registre os precos por destino e peso.",
      "Use a aba Calculadora para simular o custo de um envio.",
    ],
  },
  "torre-controle": {
    resumo: "Painel situacional mundial que junta todos os sinais de risco da operacao em uma lista unica, priorizada por gravidade.",
    itens: [
      "Separa os avisos em Sinais criticos (urgente) e Sinais de alerta (atencao).",
      "Consolida problemas de toda a cadeia: incidentes abertos, crises ativas e embarques atrasados.",
      "Mostra riscos especificos: cargas retidas na aduana, cadeia fria rompida e gargalos detectados pelo gemeo digital.",
      "Acompanha o patio e o armazem: fila no patio, docas bloqueadas.",
      "Cobre a ponta final: entregas falhas, entregas pendentes, volumes em transito e ocorrencias da transportadora.",
      "Cada item vira ponto de partida para investigar e acionar o responsavel.",
    ],
  },
  "transportadoras": {
    resumo: "Gestao do relacionamento com transportadoras (CMP): homologacao, contratos, documentos, scorecard, ranking, ocorrencias e compliance.",
    itens: [
      "Aba Painel: visao geral das transportadoras e do desempenho.",
      "Aba Transportadoras: homologacao e recalculo da nota (scorecard) de cada transportadora.",
      "Aba Scorecard & Ranking: classifica as transportadoras por entrega no prazo (OTD), ocorrencias e score.",
      "Aba Contratos: contratos comerciais com vigencia, SLA de coleta/entrega, penalidades e bonus.",
      "Aba Documentos: ANTT, seguros, licencas, certificados e alvaras com data de validade e status.",
      "Aba Ocorrencias: atrasos, avarias, extravios, roubos e nao conformidades, com severidade e plano de acao.",
    ],
  },
  "transporte": {
    resumo: "Torre de controle que acompanha as cargas em transito em tempo real, com previsao de chegada, score de risco e ocorrencias.",
    itens: [
      "Aba Painel: indicadores gerais das entregas e do desempenho no prazo (OTIF).",
      "Aba Em Transito: lista os embarques a caminho com transportadora, destino, status, ultima localizacao, previsao de chegada e risco.",
      "Aba Ocorrencias: problemas abertos (atrasos, desvios) que podem ser marcados como resolvidos.",
      "Botao Analisar risco (IA): gera uma avaliacao automatica de risco das entregas.",
      "Os embarques exibidos aqui nascem no modulo TMS.",
      "Botao Verificar agora: procura novas ocorrencias nas cargas em andamento.",
    ],
  },
  "ultima-milha": {
    resumo: "Controla a etapa final da entrega até a porta do cliente: monta rotas, sequencia as paradas do entregador, registra a prova de entrega e mede a pontualidade.",
    itens: [
      "Aba Painel: indicadores de entrega, com destaque para o OTD (percentual entregue no prazo), entregues, em rota, pendentes e falhas.",
      "Aba Rotas & Paradas: mostra cada rota e suas paradas coloridas por situação (pendente, a caminho, chegou, concluída, falhou).",
      "Aba Otimizar: reordena as paradas de uma rota para reduzir distância e recalcula o horário previsto (ETA) de cada uma.",
      "Aba Prova de Entrega (POD): registra quem recebeu, documento e comprovante da entrega.",
      "Aba Ocorrências: guarda as tentativas que falharam e o motivo.",
      "Aba Geocercas: áreas no mapa usadas para confirmar automaticamente chegada e saída dos pontos.",
    ],
    passos: [
      "Na aba Otimizar, selecione a rota e clique em Otimizar rota para sequenciar as paradas.",
      "O entregador segue as paradas na ordem definida.",
      "Ao entregar, registre a prova de entrega (POD) na aba correspondente.",
      "Se a entrega falhar, registre a ocorrência com o motivo.",
    ],
  },
  "vhsys": {
    resumo: "Mantem o estoque em sincronia com o sistema VHSYS: os saldos vem de la e cada movimento de entrada e saida e enviado de volta.",
    itens: [
      "Painel: itens com saldo, saldo total, itens abaixo do mínimo, movimentos, entradas, saídas, movimentos com erro e locais ativos.",
      "Saldos de Estoque: quanto há de cada produto/insumo, sincronizado com o VHSYS.",
      "Movimentos: as entradas e saídas enviadas ao VHSYS registrando cada baixa ou reposição.",
      "Locais de Estoque: os depósitos cadastrados no VHSYS.",
      "O VHSYS é a fonte oficial do estoque; movimentos com erro ficam sinalizados para correção.",
    ],
  },
  "visibilidade": {
    resumo: "Rastreamento ponta a ponta das cargas, com todos os eventos padronizados numa unica linha do tempo e previsao inteligente de chegada.",
    itens: [
      "Aba Rastreios: lista os envios e mostra em que fase cada um esta.",
      "As fases seguem um padrao claro: Criado, Coletado, No armazem, No hub, Embarcado, Em transito, Chegou, Aduana, Saiu para entrega, Entregue ou Devolvido.",
      "Exibe eventos capturados e a confianca media da ETA (o quanto a previsao de chegada e confiavel).",
      "Destaca o que esta No prazo e o que atrasou, para agir antes do cliente reclamar.",
      "Aba Compartilhamentos: permite liberar o rastreamento para o cliente ou parceiro acompanhar por fora.",
    ],
    passos: [
      "Na aba Rastreios, escolha o envio para ver a linha do tempo completa.",
      "Confira a fase atual e a confianca da ETA para saber se a chegada esta segura.",
      "Se precisar dar visibilidade externa, use a aba Compartilhamentos para gerar o acesso.",
    ],
  },
  "webhooks-integracoes": {
    resumo: "Painel técnico que mostra a conversa automática entre o sistema e as plataformas e transportadoras: o que foi recebido, o que foi enviado e onde houve erro.",
    itens: [
      "Painel: contadores de webhooks configurados, entregas, envios e recebidos da SisLógica, tokens e logs, destacando o que deu erro.",
      "Webhooks (Saída): cadastre uma URL para o produtor ser avisado quando um evento acontece (ex.: venda criada); cada disparo vira uma Entrega com status HTTP e tempo.",
      "Envios e Recebidos SisLógica: pedidos de envio mandados à transportadora e os avisos de status que ela devolve, com rastreio.",
      "Tokens SisLógica: senhas que autenticam os webhooks recebidos; podem ser revogadas.",
      "Logs de API: registro de todas as chamadas de integração feitas pelo sistema, com status.",
      "Logs de Webhook: cada aviso recebido das plataformas de venda, com status, motivo, comprador, valor e IP de origem.",
    ],
  },
  "wms": {
    resumo: "Cadastro e gestao dos seus armazens (centros de distribuicao, fabricas, cross-docks e operadores logisticos), com suas zonas e posicoes de armazenagem.",
    itens: [
      "Lista dos armazéns com nome, código, tipo, endereço, quantas zonas e quantas posições (bins) cada um tem.",
      "Tipos de armazém: Distribuição (CD), Fábrica, Trânsito/cross-dock ou Operador logístico (3PL).",
      "Botão para criar um novo armazém informando nome, código, tipo e endereço.",
      "Cada armazém pode ser aberto para ver o detalhe e organizar suas zonas e endereços internos.",
      "Base para o endereçamento, as tarefas, as ondas de separação e o packing acontecerem.",
    ],
    passos: [
      "Clique em Novo armazém.",
      "Informe nome (obrigatório), código, tipo e endereço.",
      "Salve e abra o armazém para configurar zonas e posições.",
    ],
  },
  "yms": {
    resumo: "Gestao de patio e docas: cadastra as docas do armazem e organiza o agendamento de recebimentos e expedicoes.",
    itens: [
      "Aba Agendamentos: janelas de horario reservadas para recebimento e expedicao nas docas.",
      "Aba Docas: cadastro de docas com codigo, armazem e tipo (recebimento, expedicao ou ambos).",
      "Status da doca: disponivel, ocupada, bloqueada ou em manutencao.",
      "Aba Patio: posicoes do patio para organizar veiculos aguardando.",
      "Cada doca fica vinculada a um armazem cadastrado.",
      "Base para agendar as operacoes sem filas e sobreposicao.",
    ],
    passos: [
      "Cadastre as docas do armazem na aba Docas.",
      "Use a aba Agendamentos para reservar horarios de carga/descarga.",
    ],
  },
  "financeiro-dre": {
    resumo: "Mostra o resultado financeiro de verdade a partir das vendas: quanto entrou (receita bruta), quanto sai em comissões de coprodução e quanto sobra para a empresa. Tudo calculado no banco, no período que você escolher.",
    itens: [
      "Cartões: receita bruta, comissão de coprodução, líquido da empresa, margem, pedidos, ticket médio, entregues e cancelados.",
      "Estrutura do resultado: receita − comissões = líquido, no formato de um DRE simplificado.",
      "Receita por estado e por canal: onde você mais fatura, para negociar frete e priorizar estoque.",
      "Botões 7/30/90/365 dias: troca a janela do período analisado.",
    ],
    passos: [
      "Puxe seus pedidos em Puxar Pedidos e apure as comissões em Coprodução.",
      "Escolha o período no topo e leia o líquido da empresa e a margem.",
    ],
  },
  "correios-central": {
    resumo: "Reúne TODAS as ferramentas dos Correios num só lugar: pré-postagem, rastreio (SRO), conferência de postagem, correção de CEP, contratos/remetente, credenciais da API e logs.",
    itens: [
      "Prepostagem: gera as pré-postagens (PPN) dos pedidos prontos para despacho.",
      "Rastreio (SRO): consulta os eventos de cada objeto pelo código de rastreio.",
      "Conferência e correção de CEP: valida endereços e ajusta o que estiver errado antes de postar.",
      "Credenciais da API: cole a chave/contrato dos Correios para habilitar as integrações.",
    ],
    passos: [
      "Cadastre o contrato/remetente e cole as credenciais da API.",
      "Gere as prepostagens e acompanhe o rastreio dos objetos.",
    ],
  },
  "ecommerce-hub": {
    resumo: "Conecta qualquer e-commerce (Shopify, WooCommerce, Nuvemshop, VTEX, Tray, Yampi…): você cola a chave da API da loja, testa a conexão e passa a puxar os pedidos de lá.",
    itens: [
      "Catálogo de plataformas: cada loja com o campo para colar a chave da API.",
      "Salvar chave: grava a credencial de forma segura (não volta para a tela) e marca a loja como conectada.",
      "Testar conexão: confirma se a chave é válida antes de puxar pedidos.",
    ],
    passos: [
      "Escolha a plataforma, cole a chave da API e clique em Salvar.",
      "Teste a conexão e depois puxe os pedidos em Puxar Pedidos.",
    ],
  },
  "relatorios": {
    resumo: "Central de relatórios gerenciais com dados reais do sistema. Cada relatório traz indicadores (KPIs), quebras por dimensão (canal, estado, produto, status…), séries por dia e tabelas exportáveis. Os números são somados no banco, não no navegador.",
    itens: [
      "Comercial & Financeiro: Vendas, Coprodução & Comissões, Fiscal & NF-e.",
      "Operação & Logística: Operacional (Pedidos), Logística & Envios, Integrações & Webhooks.",
      "Inteligência & Governança: IA/LOGIA e Auditoria & Governança.",
      "Em cada relatório dá pra trocar o período (7/30/90/365 dias) e exportar as tabelas em CSV.",
    ],
    passos: [
      "Abra a Central de Relatórios e escolha o relatório.",
      "Ajuste o período no topo e exporte o que precisar em CSV.",
    ],
  },
  "juridico": {
    resumo: "Reúne os documentos jurídicos da plataforma (minutas geradas por IA, para revisão de um advogado): privacidade, termos, cookies, segurança e conformidade com a LGPD. Os documentos públicos têm link sem login para você usar no site e no checkout.",
    itens: [
      "Documentos públicos: Política de Privacidade, Termos de Uso e Política de Cookies — cada um com um link aberto (ex.: /privacidade) para o comprador.",
      "Documentos internos: Política de Segurança da Informação, DPA (acordo de tratamento de dados) e ROPA/RIPD (registro + relatório de impacto).",
      "Cada documento abre para leitura e pode ser impresso/salvo em PDF para enviar ao advogado.",
      "São minutas: preencha os campos entre [colchetes] (razão social, CNPJ, Encarregado/DPO) e valide juridicamente antes de publicar.",
    ],
    passos: [
      "Abra o documento, revise com seu advogado e preencha os dados da empresa.",
      "Publique os links públicos (/privacidade, /termos, /cookies) no rodapé do site e no checkout.",
    ],
  },
  "rastreio": {
    resumo: "Página pública que o comprador usa para acompanhar o pedido pelo código de rastreio. Cobre tanto os pedidos logísticos quanto os pedidos de loja postados pelos Correios.",
    itens: [
      "Campo de busca: o cliente digita o código de rastreio e vê o status atual.",
      "Linha do tempo: mostra as movimentações do objeto (postado, em trânsito, entregue).",
      "Público: pode ser compartilhado com o comprador, sem login, sem expor dados sensíveis.",
    ],
    passos: [
      "Compartilhe o link /rastreio com o comprador.",
      "Ele digita o código e acompanha a entrega em tempo real.",
    ],
  },
};
