-- ════════════════════════════════════════════════════════════════════════════
-- IMPORTAÇÃO "Logística Rodrigo" (lemonlog) → GLOP  ·  M6 — REENVIOS
-- ════════════════════════════════════════════════════════════════════════════
-- Porta reenvios (reenvio de objetos/postagens) + reenvio_pagamentos (cobrança
-- de reenvio via link Asaas). Fiel ao original (todas as colunas, tipos e
-- defaults) + padrão GLOP por cima: tenant_id/company_id/branch_id, colunas de
-- auditoria, RLS por company (app.*) e triggers touch/audit.
-- produtor_id preservado como dimensão -> public.produtores_integracao(id) (M0).
-- reenvios.id permanece bigint (identity) e reenvio_pagamentos.id permanece uuid
-- — fidelidade aos tipos de PK originais. Recurso RLS: 'shipping' (envios/reenvios).
-- Nada removido; melhorias = padrão GLOP. Ver docs/rodrigo-import/PLANO-IMPORTACAO.md.
-- ════════════════════════════════════════════════════════════════════════════

-- ── reenvios (reenvio de objeto: novo código de rastreio p/ uma venda) ────────
create table if not exists public.reenvios (
  -- PK original (bigint com sequence) preservada
  id bigint primary key generated by default as identity,
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  produtor_id uuid not null references public.produtores_integracao(id),
  venda_id bigint,
  prepostagem_id bigint,
  codigo_objeto_original text,
  codigo_objeto_novo text,
  motivo text,
  status text not null default 'pendente'::text,
  observacao text,
  comprador_nome text,
  produto_nome text,
  destino_cidade text,
  destino_uf text,
  quantidade integer,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists reenvios_company_idx on public.reenvios(company_id) where deleted_at is null;
create index if not exists reenvios_produtor_idx on public.reenvios(produtor_id);
create index if not exists reenvios_venda_idx on public.reenvios(venda_id);
create index if not exists reenvios_prepostagem_idx on public.reenvios(prepostagem_id);

-- ── reenvio_pagamentos (cobrança de reenvio via link Asaas) ──────────────────
create table if not exists public.reenvio_pagamentos (
  -- PK original (uuid) preservada
  id uuid primary key default gen_random_uuid(),
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  produtor_id uuid not null references public.produtores_integracao(id),
  reenvio_id bigint references public.reenvios(id),
  venda_id bigint,
  comprador_nome text,
  comprador_email text,
  quantidade integer not null,
  preco_total numeric not null,
  link_asaas text,
  status text not null default 'pendente'::text,
  email_enviado boolean not null default false,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists reenvio_pagamentos_company_idx on public.reenvio_pagamentos(company_id) where deleted_at is null;
create index if not exists reenvio_pagamentos_produtor_idx on public.reenvio_pagamentos(produtor_id);
create index if not exists reenvio_pagamentos_reenvio_idx on public.reenvio_pagamentos(reenvio_id);
create index if not exists reenvio_pagamentos_venda_idx on public.reenvio_pagamentos(venda_id);

-- ── Triggers touch/audit (padrão GLOP) ───────────────────────────────────────
do $$ declare t text;
begin
  foreach t in array array['reenvios','reenvio_pagamentos'] loop
    execute format('drop trigger if exists trg_%s_touch on public.%s', t, t);
    execute format('create trigger trg_%s_touch before insert or update on public.%s for each row execute function app.tg_touch_row()', t, t);
    execute format('drop trigger if exists trg_%s_audit on public.%s', t, t);
    execute format('create trigger trg_%s_audit after insert or update or delete on public.%s for each row execute function app.tg_write_audit()', t, t);
  end loop;
end $$;

-- ── RLS por company (padrão GLOP · recurso 'shipping') ───────────────────────
do $$ declare t text;
begin
  foreach t in array array['reenvios','reenvio_pagamentos'] loop
    execute format('alter table public.%s enable row level security', t);
    execute format($f$create policy %1$s_select on public.%1$s for select to authenticated
      using (app.is_superadmin() or company_id in (select app.user_company_ids()))$f$, t);
    execute format($f$create policy %1$s_insert on public.%1$s for insert to authenticated
      with check (app.can_access_company(company_id) and app.has_permission('shipping.create', company_id))$f$, t);
    execute format($f$create policy %1$s_update on public.%1$s for update to authenticated
      using (app.can_access_company(company_id) and app.has_permission('shipping.update', company_id))
      with check (app.can_access_company(company_id))$f$, t);
    execute format($f$create policy %1$s_delete on public.%1$s for delete to authenticated
      using (app.is_superadmin())$f$, t);
  end loop;
exception when duplicate_object then null;
end $$;
