-- ════════════════════════════════════════════════════════════════════════════
-- IMPORTAÇÃO "Logística Rodrigo" (lemonlog) → GLOP  ·  M1 — PLANOS & PREÇOS
-- ════════════════════════════════════════════════════════════════════════════
-- Porta as regras de produto (peso/dimensões/faixas), planos por plataforma,
-- tabelas de preço (por produtor e por produto) e as faixas de frete/peso.
-- Fiel ao original (todas as colunas, tipos, defaults, checks e comentários)
-- + padrão GLOP por cima: tenant_id/company_id/branch_id, colunas de auditoria,
-- RLS por company (app.*) e triggers touch/audit.
-- produtor_id uuid references public.produtores_integracao(id) (mestre no M0).
-- Nada removido; melhorias = padrão GLOP. Ver docs/rodrigo-import/PLANO-IMPORTACAO.md.
-- ════════════════════════════════════════════════════════════════════════════

-- ── Enums de negócio ─────────────────────────────────────────────────────────
-- (Este módulo não introduz enums próprios — plataforma/plano_codigo são text no
--  original e mantidos como text por fidelidade.)

-- ── produto_regras (catálogo global de regras de embalagem/prepostagem) ───────
-- Original SEM produtor_id (tabela global) e com id BIGINT (referenciado por
-- produtor_planos.regra_id como bigint). Preservamos o tipo bigint para não
-- quebrar a FK; usamos identity no lugar da sequence owned original.
create table if not exists public.produto_regras (
  -- id original (bigint, PK) — mantido por fidelidade e por causa da FK regra_id
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  nome text not null,
  palavras_chave text[] not null default '{}'::text[],
  peso_unitario_g numeric not null default 0,
  altura_cm numeric not null default 2,
  largura_cm numeric not null default 11,
  comprimento_cm numeric not null default 16,
  valor_declarado_padrao numeric,
  faixas jsonb not null default '[]'::jsonb,
  ativo boolean not null default true,
  is_fallback boolean not null default false,
  itens_planos jsonb not null default '[]'::jsonb,
  enviar_sislogica boolean not null default true,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
comment on column public.produto_regras.enviar_sislogica is 'Quando false, produtos que casarem com esta regra não serão enviados para a SisLogica (automático e manual).';
create index if not exists produto_regras_company_idx on public.produto_regras(company_id) where deleted_at is null;

-- ── produtor_planos (planos por produtor/plataforma → regra + prepostagem) ────
create table if not exists public.produtor_planos (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  produtor_id uuid not null references public.produtores_integracao(id),
  -- campos originais (fiéis)
  plano_codigo text not null,
  plano_nome_amigavel text,
  regra_id bigint references public.produto_regras(id),
  gerar_prepostagem_auto boolean not null default false,
  ativo boolean not null default true,
  plataforma text not null default 'monetizze'::text,
  atualizar_rastreio_auto boolean not null default false,
  contrato_logistico_padrao_id uuid,
  unidades integer not null default 1,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
comment on column public.produtor_planos.unidades is 'Quantos frascos/itens este plano representa. Usado para somar quantidades de upsells/order bumps em uma mesma venda.';
create index if not exists produtor_planos_company_idx on public.produtor_planos(company_id) where deleted_at is null;
create index if not exists produtor_planos_produtor_idx on public.produtor_planos(produtor_id);
create index if not exists produtor_planos_regra_idx on public.produtor_planos(regra_id);

-- ── produtor_produto_precos (preço unitário por código de produto do produtor) ─
create table if not exists public.produtor_produto_precos (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  produtor_id uuid not null references public.produtores_integracao(id),
  -- campos originais (fiéis)
  produto_codigo text not null,
  produto_nome text,
  valor_unitario numeric not null,
  ativo boolean not null default true,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists produtor_produto_precos_company_idx on public.produtor_produto_precos(company_id) where deleted_at is null;
create index if not exists produtor_produto_precos_produtor_idx on public.produtor_produto_precos(produtor_id);

-- ── produto_precos (tabela de preço por faixa de quantidade + link Asaas) ─────
create table if not exists public.produto_precos (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  produtor_id uuid not null references public.produtores_integracao(id),
  -- campos originais (fiéis)
  produto_nome text not null,
  quantidade_min integer not null default 1,
  quantidade_max integer not null default 1,
  preco_unitario numeric not null,
  link_asaas text,
  ativo boolean not null default true,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists produto_precos_company_idx on public.produto_precos(company_id) where deleted_at is null;
create index if not exists produto_precos_produtor_idx on public.produto_precos(produtor_id);

-- ── produtor_frete_faixas (valor de frete por faixa de quantidade) ────────────
create table if not exists public.produtor_frete_faixas (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  produtor_id uuid not null references public.produtores_integracao(id),
  -- campos originais (fiéis)
  qtd_min integer not null,
  qtd_max integer not null,
  valor numeric(10,2) not null,
  observacao text,
  ativo boolean not null default true,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  -- checks originais preservados
  constraint produtor_frete_faixas_check check (qtd_max >= qtd_min),
  constraint produtor_frete_faixas_qtd_min_check check (qtd_min >= 1),
  constraint produtor_frete_faixas_valor_check check (valor >= (0)::numeric)
);
create index if not exists produtor_frete_faixas_company_idx on public.produtor_frete_faixas(company_id) where deleted_at is null;
create index if not exists produtor_frete_faixas_produtor_idx on public.produtor_frete_faixas(produtor_id);

-- ── produtor_peso_faixas (peso total por faixa de quantidade) ─────────────────
create table if not exists public.produtor_peso_faixas (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  produtor_id uuid not null references public.produtores_integracao(id),
  -- campos originais (fiéis)
  qtd_min integer not null,
  qtd_max integer not null,
  peso_total numeric(10,3) not null,
  observacao text,
  ativo boolean not null default true,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  -- checks originais preservados
  constraint produtor_peso_faixas_check check (qtd_max >= qtd_min),
  constraint produtor_peso_faixas_peso_total_check check (peso_total >= (0)::numeric),
  constraint produtor_peso_faixas_qtd_max_check check (qtd_max >= 1),
  constraint produtor_peso_faixas_qtd_min_check check (qtd_min >= 1)
);
create index if not exists produtor_peso_faixas_company_idx on public.produtor_peso_faixas(company_id) where deleted_at is null;
create index if not exists produtor_peso_faixas_produtor_idx on public.produtor_peso_faixas(produtor_id);

-- ── Triggers touch/audit (padrão GLOP) ───────────────────────────────────────
do $$ declare t text;
begin
  foreach t in array array[
    'produto_regras','produtor_planos','produtor_produto_precos',
    'produto_precos','produtor_frete_faixas','produtor_peso_faixas'
  ] loop
    execute format('drop trigger if exists trg_%s_touch on public.%s', t, t);
    execute format('create trigger trg_%s_touch before insert or update on public.%s for each row execute function app.tg_touch_row()', t, t);
    execute format('drop trigger if exists trg_%s_audit on public.%s', t, t);
    execute format('create trigger trg_%s_audit after insert or update or delete on public.%s for each row execute function app.tg_write_audit()', t, t);
  end loop;
end $$;

-- ── RLS por company (padrão GLOP) ────────────────────────────────────────────
-- Recurso por tabela: preços/planos de logística = 'shipping' (correios/frete/peso/
-- prepostagem); planos e tabelas de preço puro sem afinidade específica = 'admin'.
do $$ declare rec text; t text; res text;
begin
  foreach rec in array array[
    'produto_regras:shipping',
    'produtor_planos:shipping',
    'produtor_frete_faixas:shipping',
    'produtor_peso_faixas:shipping',
    'produtor_produto_precos:admin',
    'produto_precos:admin'
  ] loop
    t   := split_part(rec, ':', 1);
    res := split_part(rec, ':', 2);
    execute format('alter table public.%s enable row level security', t);
    execute format($f$create policy %1$s_select on public.%1$s for select to authenticated
      using (app.is_superadmin() or company_id in (select app.user_company_ids()))$f$, t);
    execute format($f$create policy %1$s_insert on public.%1$s for insert to authenticated
      with check (app.can_access_company(company_id) and app.has_permission('%2$s.create', company_id))$f$, t, res);
    execute format($f$create policy %1$s_update on public.%1$s for update to authenticated
      using (app.can_access_company(company_id) and app.has_permission('%2$s.update', company_id))
      with check (app.can_access_company(company_id))$f$, t, res);
    execute format($f$create policy %1$s_delete on public.%1$s for delete to authenticated
      using (app.is_superadmin())$f$, t);
  end loop;
exception when duplicate_object then null;
end $$;
