-- ════════════════════════════════════════════════════════════════════════════
-- IMPORTAÇÃO "Logística Rodrigo" (lemonlog) → GLOP  ·  M9 — NF-e (EMISSÃO FISCAL)
-- ════════════════════════════════════════════════════════════════════════════
-- Porta: nfe_emissoes (fila/histórico de emissão de NF-e via vhsys) e
-- nfe_baixa_estoque_config (mapeamento produto↔vhsys p/ baixa de estoque na NF-e).
-- Fiel ao original (todas as colunas, tipos e defaults) + padrão GLOP por cima:
-- tenant_id/company_id/branch_id, colunas de auditoria, RLS por company (app.*),
-- triggers touch/audit. produtor_id → FK public.produtores_integracao(id) (M0).
-- Resource RLS = 'inventory' (nfe/vhsys/estoque). Nada removido; melhorias = GLOP.
-- Ver docs/rodrigo-import/PLANO-IMPORTACAO.md.
-- ════════════════════════════════════════════════════════════════════════════

-- ── nfe_baixa_estoque_config (mapa produto→vhsys p/ baixa de estoque) ─────────
create table if not exists public.nfe_baixa_estoque_config (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  produtor_id uuid not null references public.produtores_integracao(id),
  produto_codigo text not null default ''::text,
  id_produto_vhsys text not null,
  id_local_estoque text,
  produto_descricao text,
  local_descricao text,
  ativo boolean not null default true,
  match_nome text,
  vincular_produto boolean not null default true,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists nfe_baixa_estoque_config_company_idx on public.nfe_baixa_estoque_config(company_id) where deleted_at is null;
create index if not exists nfe_baixa_estoque_config_produtor_idx on public.nfe_baixa_estoque_config(produtor_id);

-- ── nfe_emissoes (fila/histórico de emissão de NF-e) ─────────────────────────
-- Original: id bigint (sequence). Preservado como identity p/ fidelidade;
-- venda_id permanece bigint (referência à venda original).
create table if not exists public.nfe_emissoes (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  venda_id bigint,
  produtor_id uuid references public.produtores_integracao(id),
  status text not null default 'pendente'::text,
  vhsys_nfe_id text,
  chave text,
  protocolo text,
  ambiente text,
  danfe_url text,
  xml_url text,
  valor numeric,
  produto_codigo text,
  produto_nome text,
  plano_codigo text,
  plano_nome text,
  erro text,
  tentativas integer not null default 0,
  payload_request jsonb,
  payload_response jsonb,
  emitida_at timestamptz,
  -- colunas-padrão GLOP
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists nfe_emissoes_company_idx on public.nfe_emissoes(company_id) where deleted_at is null;
create index if not exists nfe_emissoes_produtor_idx on public.nfe_emissoes(produtor_id);
create index if not exists nfe_emissoes_venda_idx on public.nfe_emissoes(venda_id);
create index if not exists nfe_emissoes_status_idx on public.nfe_emissoes(status);

-- ── Triggers touch/audit (padrão GLOP) ───────────────────────────────────────
do $$ declare t text;
begin
  foreach t in array array['nfe_baixa_estoque_config','nfe_emissoes'] loop
    execute format('drop trigger if exists trg_%s_touch on public.%s', t, t);
    execute format('create trigger trg_%s_touch before insert or update on public.%s for each row execute function app.tg_touch_row()', t, t);
    execute format('drop trigger if exists trg_%s_audit on public.%s', t, t);
    execute format('create trigger trg_%s_audit after insert or update or delete on public.%s for each row execute function app.tg_write_audit()', t, t);
  end loop;
end $$;

-- ── RLS por company (padrão GLOP · resource 'inventory') ─────────────────────
do $$ declare t text;
begin
  foreach t in array array['nfe_baixa_estoque_config','nfe_emissoes'] loop
    execute format('alter table public.%s enable row level security', t);
    execute format($f$create policy %1$s_select on public.%1$s for select to authenticated
      using (app.is_superadmin() or company_id in (select app.user_company_ids()))$f$, t);
    execute format($f$create policy %1$s_insert on public.%1$s for insert to authenticated
      with check (app.can_access_company(company_id) and app.has_permission('inventory.create', company_id))$f$, t);
    execute format($f$create policy %1$s_update on public.%1$s for update to authenticated
      using (app.can_access_company(company_id) and app.has_permission('inventory.update', company_id))
      with check (app.can_access_company(company_id))$f$, t);
    execute format($f$create policy %1$s_delete on public.%1$s for delete to authenticated
      using (app.is_superadmin())$f$, t);
  end loop;
exception when duplicate_object then null;
end $$;
