-- ════════════════════════════════════════════════════════════════════════════
-- IMPORTAÇÃO "Logística Rodrigo" (lemonlog) → GLOP  ·  M10 — COMUNICAÇÃO
-- ════════════════════════════════════════════════════════════════════════════
-- Porta o módulo de comunicação com o comprador: logs de envio de e-mail
-- (SendGrid) e de WhatsApp de rastreio, mais os templates editáveis (singleton)
-- de e-mail e WhatsApp (inclui o template do "carteiro").
-- Fiel ao original (todas as colunas, tipos, defaults e constraints) + padrão
-- GLOP por cima: tenant_id/company_id/branch_id, colunas de auditoria,
-- RLS por company (app.*) e triggers touch/audit.
-- PKs originais preservadas: bigint (identity) nos logs; integer singleton
-- (CHECK id = 1) nos templates. Nenhuma coluna removida.
-- Recurso RLS: 'shipping' (comunicação de envios/rastreio/Correios).
-- Observação: as tabelas de origem NÃO possuem produtor_id — a dimensão de
-- tenancy aqui é company_id (GLOP). Nenhum produtor_id foi inventado (fidelidade).
-- Ver docs/rodrigo-import/PLANO-IMPORTACAO.md. Melhorias = padrão GLOP.
-- ════════════════════════════════════════════════════════════════════════════

-- ── email_envios_log (log de envio de e-mail de rastreio via SendGrid) ───────
create table if not exists public.email_envios_log (
  -- PK original (bigint com sequence) preservada
  id bigint primary key generated by default as identity,
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  pedido_id uuid,
  venda_id bigint,
  codigo_rastreio text,
  email text not null,
  nome text,
  status text not null default 'queued'::text,
  erro text,
  sendgrid_message_id text,
  assunto text,
  template_hash text,
  -- colunas-padrão GLOP (created_at original preservado)
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists email_envios_log_company_idx on public.email_envios_log(company_id) where deleted_at is null;
create index if not exists email_envios_log_pedido_idx on public.email_envios_log(pedido_id);
create index if not exists email_envios_log_venda_idx on public.email_envios_log(venda_id);
create index if not exists email_envios_log_rastreio_idx on public.email_envios_log(codigo_rastreio);
create index if not exists email_envios_log_status_idx on public.email_envios_log(status);

-- ── email_template_rastreio (template singleton do e-mail de rastreio) ───────
-- Singleton original preservado (id integer default 1 + CHECK id = 1).
create table if not exists public.email_template_rastreio (
  -- PK original (integer singleton) preservada
  id integer primary key not null default 1,
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  assunto text not null default 'Seu código de rastreio - Pedido {{codigo}}'::text,
  html text not null default '<div style="font-family:Arial,sans-serif;max-width:560px;margin:0 auto;padding:20px;color:#222"><h2 style="margin:0 0 16px">Olá, {{nome}}!</h2><p>Seu pedido foi postado nos Correios. Veja abaixo o código de rastreio:</p><p style="font-size:18px;font-weight:bold;background:#f4f4f4;padding:12px;border-radius:6px;text-align:center;letter-spacing:1px">{{codigo}}</p><p>Você pode acompanhar a entrega clicando no link abaixo:</p><p style="text-align:center;margin:24px 0"><a href="{{link_rastreio}}" style="background:#0066cc;color:#fff;padding:12px 24px;text-decoration:none;border-radius:6px;display:inline-block">Rastrear pedido</a></p></div>'::text,
  -- colunas-padrão GLOP (updated_at original preservado)
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  -- constraint original preservada
  constraint email_template_rastreio_singleton check ((id = 1))
);
create index if not exists email_template_rastreio_company_idx on public.email_template_rastreio(company_id) where deleted_at is null;

-- ── whatsapp_envios_log (log de envio de WhatsApp) ───────────────────────────
create table if not exists public.whatsapp_envios_log (
  -- PK original (bigint com sequence) preservada
  id bigint primary key generated by default as identity,
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  cliente_id bigint,
  telefone text not null,
  nome text,
  mensagem text not null,
  status text not null default 'pendente'::text,
  erro text,
  enviado_at timestamptz,
  -- colunas-padrão GLOP (created_at original preservado)
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create index if not exists whatsapp_envios_log_company_idx on public.whatsapp_envios_log(company_id) where deleted_at is null;
create index if not exists whatsapp_envios_log_cliente_idx on public.whatsapp_envios_log(cliente_id);
create index if not exists whatsapp_envios_log_telefone_idx on public.whatsapp_envios_log(telefone);
create index if not exists whatsapp_envios_log_status_idx on public.whatsapp_envios_log(status);

-- ── whatsapp_template (template singleton da mensagem de WhatsApp) ───────────
-- Singleton original preservado (id integer default 1 + CHECK id = 1).
create table if not exists public.whatsapp_template (
  -- PK original (integer singleton) preservada
  id integer primary key not null default 1,
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  mensagem text not null default 'Olá {nome}! 📦

Seu pedido do plano *{plano}* foi enviado pelos Correios.

🔎 Código de rastreio: *{codigo_rastreio}*

Acompanhe em:
https://rastreamento.correios.com.br/app/index.php

Qualquer dúvida estamos à disposição!'::text,
  -- colunas-padrão GLOP (updated_at original preservado)
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  -- constraint original preservada
  constraint single_row check ((id = 1))
);
create index if not exists whatsapp_template_company_idx on public.whatsapp_template(company_id) where deleted_at is null;

-- ── whatsapp_template_carteiro (template singleton "carteiro") ───────────────
-- Singleton original preservado (id integer default 1 + CHECK id = 1).
create table if not exists public.whatsapp_template_carteiro (
  -- PK original (integer singleton) preservada
  id integer primary key not null default 1,
  -- colunas-padrão GLOP (multi-tenant)
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  -- campos originais (fiéis)
  mensagem text not null,
  -- colunas-padrão GLOP (updated_at original preservado)
  active boolean not null default true, version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  deleted_at timestamptz, deleted_by uuid references auth.users(id), reason_deleted text,
  created_by uuid references auth.users(id), updated_by uuid references auth.users(id),
  -- constraint original preservada
  constraint single_row_carteiro check ((id = 1))
);
create index if not exists whatsapp_template_carteiro_company_idx on public.whatsapp_template_carteiro(company_id) where deleted_at is null;

-- ── Triggers touch/audit (padrão GLOP) ───────────────────────────────────────
do $$ declare t text;
begin
  foreach t in array array['email_envios_log','email_template_rastreio','whatsapp_envios_log','whatsapp_template','whatsapp_template_carteiro'] loop
    execute format('drop trigger if exists trg_%s_touch on public.%s', t, t);
    execute format('create trigger trg_%s_touch before insert or update on public.%s for each row execute function app.tg_touch_row()', t, t);
    execute format('drop trigger if exists trg_%s_audit on public.%s', t, t);
    execute format('create trigger trg_%s_audit after insert or update or delete on public.%s for each row execute function app.tg_write_audit()', t, t);
  end loop;
end $$;

-- ── RLS por company (padrão GLOP) — recurso 'shipping' ───────────────────────
do $$ declare t text;
begin
  foreach t in array array['email_envios_log','email_template_rastreio','whatsapp_envios_log','whatsapp_template','whatsapp_template_carteiro'] loop
    execute format('alter table public.%s enable row level security', t);
    execute format($f$create policy %1$s_select on public.%1$s for select to authenticated
      using (app.is_superadmin() or company_id in (select app.user_company_ids()))$f$, t);
    execute format($f$create policy %1$s_insert on public.%1$s for insert to authenticated
      with check (app.can_access_company(company_id) and app.has_permission('shipping.create', company_id))$f$, t);
    execute format($f$create policy %1$s_update on public.%1$s for update to authenticated
      using (app.can_access_company(company_id) and app.has_permission('shipping.update', company_id))
      with check (app.can_access_company(company_id))$f$, t);
    execute format($f$create policy %1$s_delete on public.%1$s for delete to authenticated
      using (app.is_superadmin())$f$, t);
  end loop;
exception when duplicate_object then null;
end $$;
