-- ════════════════════════════════════════════════════════════════════════════
-- IMPORTAÇÃO "Logística Rodrigo" (lemonlog) → GLOP  ·  M4 — CORREIOS / PRÉ-POSTAGEM
-- ════════════════════════════════════════════════════════════════════════════
-- Porta o ciclo de pré-postagem e integração com os Correios: prepostagens (+ PPN),
-- logs de automação, prepostagem em massa, conferência de postagem, logs de API,
-- cache de token dos Correios e logs de correção de CEP.
-- Fiel ao original (TODAS as colunas, tipos e defaults) + padrão GLOP por cima:
-- tenant_id/company_id/branch_id, colunas de auditoria, RLS por company (app.*)
-- e triggers touch/audit. PKs originais preservadas (bigint/integer/uuid).
-- produtor_id → FK public.produtores_integracao(id) quando existir na origem.
-- Sem enums neste módulo (campos status/etapa são text livre no original).
-- Módulo classificado como resource 'shipping' (logística/correios/envios).
-- Ver docs/rodrigo-import/PLANO-IMPORTACAO.md. Nada removido; melhorias = padrão GLOP.
-- ════════════════════════════════════════════════════════════════════════════

-- ── prepostagens (pré-postagem gerada p/ os Correios + snapshot de rastreio) ──
create table if not exists public.prepostagens (
  id bigint generated by default as identity primary key,
  -- campos originais (fiéis)
  venda_id bigint,
  regra_id bigint,
  quantidade integer not null default 1,
  servico_codigo text not null,
  servico_nome text,
  peso_g numeric not null,
  altura_cm numeric not null,
  largura_cm numeric not null,
  comprimento_cm numeric not null,
  valor_declarado numeric,
  destinatario_nome text,
  destinatario_cep text,
  destinatario_endereco text,
  destinatario_cidade text,
  destinatario_estado text,
  codigo_objeto text,
  id_prepostagem text,
  etiqueta_pdf_base64 text,
  status text not null default 'pendente',
  erro text,
  payload_request jsonb,
  payload_response jsonb,
  ultimo_status text,
  ultimo_status_data timestamptz,
  ultimo_status_local text,
  ultima_consulta timestamptz,
  eventos_rastreio jsonb,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
alter table public.prepostagens replica identity full;
create index if not exists prepostagens_company_idx on public.prepostagens(company_id) where deleted_at is null;
create index if not exists prepostagens_venda_idx on public.prepostagens(venda_id);
create index if not exists prepostagens_codigo_objeto_idx on public.prepostagens(codigo_objeto);
create index if not exists prepostagens_status_idx on public.prepostagens(status);

-- ── prepostagens_ppn (espelho da Plataforma Pré-Postagem Nacional / PPN) ──────
create table if not exists public.prepostagens_ppn (
  id bigint generated by default as identity primary key,
  -- campos originais (fiéis)
  id_prepostagem text not null,
  codigo_objeto text,
  destinatario_nome text,
  data_postagem timestamptz,
  data_criacao timestamptz,
  data_expiracao timestamptz,
  status text not null,
  servico_codigo text,
  servico_nome text,
  destinatario_cidade text,
  destinatario_estado text,
  destinatario_cep text,
  valor_total numeric,
  payload_completo jsonb,
  ultima_sincronizacao timestamptz not null default now(),
  ultimo_status text,
  ultimo_status_data timestamptz,
  ultimo_status_local text,
  ultima_consulta_sro timestamptz,
  eventos_rastreio jsonb,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
alter table public.prepostagens_ppn replica identity full;
create index if not exists prepostagens_ppn_company_idx on public.prepostagens_ppn(company_id) where deleted_at is null;
create index if not exists prepostagens_ppn_id_prepostagem_idx on public.prepostagens_ppn(id_prepostagem);
create index if not exists prepostagens_ppn_codigo_objeto_idx on public.prepostagens_ppn(codigo_objeto);

-- ── prepostagem_auto_logs (trilha da automação de pré-postagem por etapa) ─────
create table if not exists public.prepostagem_auto_logs (
  id bigint generated by default as identity primary key,
  -- campos originais (fiéis)
  produtor_id uuid references public.produtores_integracao(id),
  venda_id bigint,
  plataforma text,
  plano_codigo text,
  plano_id uuid,
  etapa text not null,
  status text not null,
  mensagem text,
  prepostagem_id bigint,
  codigo_objeto text,
  payload jsonb,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
create index if not exists prepostagem_auto_logs_company_idx on public.prepostagem_auto_logs(company_id) where deleted_at is null;
create index if not exists prepostagem_auto_logs_produtor_idx on public.prepostagem_auto_logs(produtor_id);
create index if not exists prepostagem_auto_logs_venda_idx on public.prepostagem_auto_logs(venda_id);
create index if not exists prepostagem_auto_logs_prepostagem_idx on public.prepostagem_auto_logs(prepostagem_id);

-- ── prep_massa_logs (log da geração de pré-postagens em massa por run_id) ──────
create table if not exists public.prep_massa_logs (
  id bigint generated by default as identity primary key,
  -- campos originais (fiéis)
  run_id uuid not null,
  produtor_id uuid references public.produtores_integracao(id),
  user_id uuid,
  venda_id bigint,
  codigo_venda text,
  comprador_nome text,
  servico_codigo text,
  servico_nome text,
  quantidade integer,
  valor_declarado numeric,
  peso_g numeric,
  altura_cm numeric,
  largura_cm numeric,
  comprimento_cm numeric,
  status text not null,
  mensagem text,
  detalhes jsonb,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
create index if not exists prep_massa_logs_company_idx on public.prep_massa_logs(company_id) where deleted_at is null;
create index if not exists prep_massa_logs_produtor_idx on public.prep_massa_logs(produtor_id);
create index if not exists prep_massa_logs_run_idx on public.prep_massa_logs(run_id);
create index if not exists prep_massa_logs_venda_idx on public.prep_massa_logs(venda_id);

-- ── conferencias_postagem (conferência planilha × PDF de postados) ────────────
create table if not exists public.conferencias_postagem (
  id uuid primary key default gen_random_uuid(),
  -- campos originais (fiéis)
  user_id uuid not null,
  produtor_id uuid references public.produtores_integracao(id),
  planilha_nome text,
  pdf_nome text,
  total_planilha integer not null default 0,
  total_postados integer not null default 0,
  total_nao_encontrados integer not null default 0,
  total_possiveis integer not null default 0,
  resultado jsonb not null default '[]'::jsonb,
  paginas_resumo jsonb not null default '[]'::jsonb,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
create index if not exists conferencias_postagem_company_idx on public.conferencias_postagem(company_id) where deleted_at is null;
create index if not exists conferencias_postagem_produtor_idx on public.conferencias_postagem(produtor_id);
create index if not exists conferencias_postagem_user_idx on public.conferencias_postagem(user_id);

-- ── correios_api_logs (trilha de chamadas à API dos Correios) ─────────────────
create table if not exists public.correios_api_logs (
  id bigint generated by default as identity primary key,
  -- campos originais (fiéis)
  prefixo text not null,
  acao text not null,
  status text not null,
  http_status integer,
  codigo_rastreio text,
  mensagem text,
  request_payload jsonb,
  response_payload jsonb,
  duracao_ms integer,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
create index if not exists correios_api_logs_company_idx on public.correios_api_logs(company_id) where deleted_at is null;
create index if not exists correios_api_logs_codigo_rastreio_idx on public.correios_api_logs(codigo_rastreio);
create index if not exists correios_api_logs_acao_idx on public.correios_api_logs(acao);

-- ── correios_token_cache (cache de tokens de autenticação dos Correios) ───────
create table if not exists public.correios_token_cache (
  id integer generated by default as identity primary key,
  -- campos originais (fiéis)
  tipo text not null,
  numero_cartao text,
  token text not null,
  expires_at timestamptz not null,
  refreshed_at timestamptz not null default now(),
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
create index if not exists correios_token_cache_company_idx on public.correios_token_cache(company_id) where deleted_at is null;
create index if not exists correios_token_cache_tipo_idx on public.correios_token_cache(tipo);

-- ── cep_correcao_logs (auditoria de correção de CEP e envio ao SISLOG) ────────
create table if not exists public.cep_correcao_logs (
  id bigint generated by default as identity primary key,
  -- campos originais (fiéis)
  produtor_id uuid references public.produtores_integracao(id),
  venda_id bigint,
  pedido_id uuid,
  destino text,
  cep_original text,
  cep_corrigido text not null,
  fonte text,
  endereco_original jsonb,
  endereco_corrigido jsonb,
  enviado_sislog boolean not null default false,
  observacao text,
  -- colunas-padrão GLOP
  tenant_id uuid not null,
  company_id uuid,
  branch_id uuid,
  active boolean not null default true,
  version integer not null default 1,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  reason_deleted text,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id)
);
create index if not exists cep_correcao_logs_company_idx on public.cep_correcao_logs(company_id) where deleted_at is null;
create index if not exists cep_correcao_logs_produtor_idx on public.cep_correcao_logs(produtor_id);
create index if not exists cep_correcao_logs_venda_idx on public.cep_correcao_logs(venda_id);
create index if not exists cep_correcao_logs_pedido_idx on public.cep_correcao_logs(pedido_id);

-- ── Triggers touch/audit (padrão GLOP) ───────────────────────────────────────
do $$ declare t text;
begin
  foreach t in array array[
    'prepostagens','prepostagens_ppn','prepostagem_auto_logs','prep_massa_logs',
    'conferencias_postagem','correios_api_logs','correios_token_cache','cep_correcao_logs'
  ] loop
    execute format('drop trigger if exists trg_%s_touch on public.%s', t, t);
    execute format('create trigger trg_%s_touch before insert or update on public.%s for each row execute function app.tg_touch_row()', t, t);
    execute format('drop trigger if exists trg_%s_audit on public.%s', t, t);
    execute format('create trigger trg_%s_audit after insert or update or delete on public.%s for each row execute function app.tg_write_audit()', t, t);
  end loop;
end $$;

-- ── RLS por company (padrão GLOP) — resource 'shipping' ───────────────────────
do $$ declare t text;
begin
  foreach t in array array[
    'prepostagens','prepostagens_ppn','prepostagem_auto_logs','prep_massa_logs',
    'conferencias_postagem','correios_api_logs','correios_token_cache','cep_correcao_logs'
  ] loop
    execute format('alter table public.%s enable row level security', t);
    execute format($f$create policy %1$s_select on public.%1$s for select to authenticated
      using (app.is_superadmin() or company_id in (select app.user_company_ids()))$f$, t);
    execute format($f$create policy %1$s_insert on public.%1$s for insert to authenticated
      with check (app.can_access_company(company_id) and app.has_permission('shipping.create', company_id))$f$, t);
    execute format($f$create policy %1$s_update on public.%1$s for update to authenticated
      using (app.can_access_company(company_id) and app.has_permission('shipping.update', company_id))
      with check (app.can_access_company(company_id))$f$, t);
    execute format($f$create policy %1$s_delete on public.%1$s for delete to authenticated
      using (app.is_superadmin())$f$, t);
  end loop;
exception when duplicate_object then null;
end $$;
